#pragma once
// -----------------------------------------------------------------------
// KonScript C++ Code Generator
// Walks the AST and emits C++ that links against KonEngine.
// -----------------------------------------------------------------------
#include "ast.hpp"
#include <string>
#include <sstream>
#include <vector>
#include <unordered_set>
#include <unordered_map>

namespace KonScript {

class Codegen {
public:
    struct Error {
        std::string message;
        int line, col;
    };

    const std::vector<e>& errors() const { return m_errors; }
    bool hasErrors() const { return !m_errors.empty(); }

    enum class Target {
        Engine,
        Standalone,
    };

    void setTarget(Target t) { m_target = t; }
    Target target() const    { return m_target; }

    std::string generate(const Program& prog) {
        m_out.str("");
        m_indent     = 0;
        m_atTopLevel = true;
        m_sceneVars.clear();
        m_nodeTypeNames.clear();

        line("// Generated by KonScript v0.1.0 -- do not edit");
        line("// Source: " + prog.filename);
        if (m_target == Target::Engine)
            line("#include \"KonEngine.hpp\"");
        line("#include <string>");
        line("#include <vector>");
        line("#include <functional>");
        line("#include <optional>");
        line("#include <cstdio>");
        line("#include <cstdint>");
        line("#include <tuple>");
        line("");

        for (auto& s : prog.stmts)
            if (s->kind == Stmt::Kind::NodeDecl   ||
                s->kind == Stmt::Kind::StructDecl ||
                s->kind == Stmt::Kind::ClassDecl  ||
                s->kind == Stmt::Kind::EnumDecl)
                forwardDeclare(s.get());
        line("");

        for (auto& s : prog.stmts)
            genTopLevel(s.get());

        return m_out.str();
    }

private:
    std::ostringstream              m_out;
    int                             m_indent     = 0;
    bool                            m_atTopLevel = true;
    Target                          m_target     = Target::Standalone;
    std::vector<e>              m_errors;
    std::unordered_set<std::string> m_enumNames;
    std::unordered_set<std::string> m_sceneVars;      // variables of type Scene
    std::unordered_set<std::string> m_nodeTypeNames;  // user-declared node types

    void error(const std::string& msg, int l = 0, int c = 0) {
        m_errors.push_back({msg, l, c});
    }

    void write(const std::string& s) { m_out << s; }
    void line(const std::string& s = "") {
        m_out << std::string(m_indent * 4, ' ') << s << "\n";
    }
    void indent() { m_indent++; }
    void dedent() { if (m_indent > 0) m_indent--; }

    // -----------------------------------------------------------------------
    // Type conversion
    // -----------------------------------------------------------------------
    std::string cppType(const TypeAnnotation& ta) {
        if (ta.isTuple) {
            std::string s = "std::tuple<";
            for (size_t i = 0; i < ta.tupleTypes.size(); i++) {
                if (i > 0) s += ", ";
                s += cppType(ta.tupleTypes[i]);
            }
            return s + ">";
        }
        if (ta.isArray) {
            TypeAnnotation inner; inner.base = ta.base;
            std::string elem = cppType(inner);
            if (ta.arraySize >= 0)
                return "std::array<" + elem + ", " + std::to_string(ta.arraySize) + ">";
            return "std::vector<" + elem + ">";
        }
        std::string base = cppBaseType(ta.base);
        if (ta.nullable) return "std::optional<" + base + ">";
        return base;
    }

    std::string cppBaseType(const std::string& name) {
        if (name == "I8")     return "int8_t";
        if (name == "I16")    return "int16_t";
        if (name == "I32")    return "int32_t";
        if (name == "I64")    return "int64_t";
        if (name == "U8")     return "uint8_t";
        if (name == "U16")    return "uint16_t";
        if (name == "U32")    return "uint32_t";
        if (name == "U64")    return "uint64_t";
        if (name == "F32")    return "float";
        if (name == "F64")    return "double";
        if (name == "Bool")   return "bool";
        if (name == "str")    return "const char*";
        if (name == "String") return "std::string";
        if (name == "Vec2")   return "Vector2";
        if (name == "void")   return "void";
        if (name == "Scene")  return "Scene";
        static const std::unordered_set<std::string> builtinNodes = {
            "Node","Node2D","Sprite2D","Collider2D","AnimationPlayer","Camera2D"
        };
        if (builtinNodes.count(name))      return name + "*";
        if (m_nodeTypeNames.count(name))   return name + "*";
        return name;
    }

    bool isPrimitive(const TypeAnnotation& ta) {
        if (ta.isTuple || ta.isArray || ta.nullable) return false;
        const std::string& b = ta.base;
        return b=="I8"||b=="I16"||b=="I32"||b=="I64"
            || b=="U8"||b=="U16"||b=="U32"||b=="U64"
            || b=="F32"||b=="F64"||b=="Bool";
    }

    // -----------------------------------------------------------------------
    // Forward declarations
    // -----------------------------------------------------------------------
    void forwardDeclare(const Stmt* s) {
        switch (s->kind) {
            case Stmt::Kind::StructDecl:
                line("struct " + static_cast<const StructDecl*>(s)->name + ";");
                break;
            case Stmt::Kind::ClassDecl:
                line("class " + static_cast<const ClassDecl*>(s)->name + ";");
                break;
            case Stmt::Kind::NodeDecl: {
                auto* n = static_cast<const NodeDecl*>(s);
                line("class " + n->name + ";");
                m_nodeTypeNames.insert(n->name);
                break;
            }
            case Stmt::Kind::EnumDecl:
                m_enumNames.insert(static_cast<const EnumDecl*>(s)->name);
                break;
            default: break;
        }
    }

    // -----------------------------------------------------------------------
    // Top-level
    // -----------------------------------------------------------------------
    void genTopLevel(const Stmt* s) {
        m_atTopLevel = true;
        switch (s->kind) {
            case Stmt::Kind::Include:    genInclude(s);  break;
            case Stmt::Kind::Const:      genConst(s);    break;
            case Stmt::Kind::EnumDecl:   genEnum(s);     break;
            case Stmt::Kind::StructDecl: genStruct(s);   break;
            case Stmt::Kind::ClassDecl:  genClass(s);    break;
            case Stmt::Kind::NodeDecl:   genNode(s);     break;
            case Stmt::Kind::FuncDecl:
                genFuncDecl(static_cast<const FuncDecl*>(s), "");
                break;
            case Stmt::Kind::Let: genLet(s); break;
            default: break;
        }
    }

    void genInclude(const Stmt* s) {
        auto* i = static_cast<const IncludeStmt*>(s);
        if (i->path == "engine") return;
        if (i->isSystem) line("#include <" + i->path + ">");
        else             line("#include \"" + i->path + "\"");
    }

    // BUG-09: top-level -> constexpr, function scope -> const
    void genConst(const Stmt* s) {
        auto* c = static_cast<const ConstStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write((m_atTopLevel ? "constexpr " : "const ") + cppType(c->type) + " " + c->name + " = ");
        genExpr(c->init.get());
        write(";\n");
    }

    // BUG-08: enum helpers in namespace
    void genEnum(const Stmt* s) {
        auto* e = static_cast<const EnumDecl*>(s);
        bool hasPayload = false;
        for (auto& v : e->variants)
            if (v.payload) { hasPayload = true; break; }

        if (!hasPayload) {
            line("enum class " + e->name + " {");
            indent();
            for (auto& v : e->variants) line(v.name + ",");
            dedent();
            line("};");
        } else {
            line("// Enum: " + e->name);
            for (auto& v : e->variants) {
                if (v.payload)
                    line("struct " + e->name + "_" + v.name + " { " + cppType(*v.payload) + " value; };");
                else
                    line("struct " + e->name + "_" + v.name + " {};");
            }
            write("using " + e->name + " = std::variant<");
            bool first = true;
            for (auto& v : e->variants) {
                if (!first) write(", ");
                first = false;
                write(e->name + "_" + v.name);
            }
            write(">;\n");
            line("namespace " + e->name + "_ {");
            for (auto& v : e->variants) {
                write("    inline ::" + e->name + " " + v.name);
                if (v.payload)
                    write("(" + cppType(*v.payload) + " val) { return ::" + e->name + "_" + v.name + "{val}; }\n");
                else
                    write("() { return ::" + e->name + "_" + v.name + "{}; }\n");
            }
            line("}");
        }
        line("");
    }

    void genStruct(const Stmt* s) {
        auto* st = static_cast<const StructDecl*>(s);
        line("struct " + st->name + " {");
        indent();
        for (auto& f : st->fields) {
            write(std::string(m_indent * 4, ' '));
            write(cppType(f.type) + " " + f.name);
            if (f.init) { write(" = "); genExpr(f.init.get()); }
            write(";\n");
        }
        dedent();
        line("};");
        line("");
    }

    void genClass(const Stmt* s) {
        auto* c = static_cast<const ClassDecl*>(s);
        std::string decl = "class " + c->name;
        if (!c->base.empty()) decl += " : public " + c->base;
        line(decl + " {");
        line("public:");
        indent();
        for (auto& f : c->fields) {
            write(std::string(m_indent * 4, ' '));
            write(cppType(f.type) + " " + f.name);
            if (f.init) { write(" = "); genExpr(f.init.get()); }
            write(";\n");
        }
        if (!c->fields.empty()) line("");
        for (auto& m : c->methods) genFuncDecl(m.get(), "");
        dedent();
        line("};");
        line("");
    }

    void genNode(const Stmt* s) {
        auto* n = static_cast<const NodeDecl*>(s);
        if (m_target == Target::Standalone)
            line("class " + n->name + " {");
        else
            line("class " + n->name + " : public " + n->base + " {");
        line("public:");
        indent();

        if (m_target == Target::Engine)
            line(n->name + "(const std::string& name) : " + n->base + "(name) {}");
        else
            line(n->name + "() {}");
        line("");

        for (auto& f : n->fields) {
            write(std::string(m_indent * 4, ' '));
            write(cppType(f.type) + " " + f.name);
            if (f.init) { write(" = "); genExpr(f.init.get()); }
            write(";\n");
        }
        if (!n->fields.empty()) line("");

        for (auto& m : n->methods) genNodeMethod(m.get(), n->name);

        dedent();
        line("};");
        line("");
    }

    void genNodeMethod(const FuncDecl* f, const std::string&) {
        struct MM { std::string ks, sig; };
        static const std::vector<MM> builtins = {
            {"Ready",            "void Ready() override"},
            {"Update",           "void Update(float dt) override"},
            {"Draw",             "void Draw() override"},
            {"OnCollisionEnter", "void OnCollisionEnter(Collider2D* other) override"},
            {"OnCollisionExit",  "void OnCollisionExit(Collider2D* other) override"},
        };
        for (auto& bm : builtins) {
            if (f->name == bm.ks) {
                line(bm.sig + " {");
                indent();
                m_atTopLevel = false;
                genBlock(f->body.get());
                dedent();
                line("}");
                line("");
                return;
            }
        }
        genFuncDecl(f, "");
    }

    void genFuncDecl(const FuncDecl* f, const std::string& prefix) {
        std::string ret = f->returnType ? cppType(*f->returnType) : "void";
        write(std::string(m_indent * 4, ' '));
        write(ret + " " + (prefix.empty() ? "" : prefix + "::") + f->name + "(");
        for (size_t i = 0; i < f->params.size(); i++) {
            if (i > 0) write(", ");
            write(cppType(f->params[i].type) + " " + f->params[i].name);
        }
        write(") {\n");
        indent();
        m_atTopLevel = false;
        genBlock(f->body.get());
        dedent();
        line("}");
        line("");
    }

    // -----------------------------------------------------------------------
    // Statements
    // -----------------------------------------------------------------------
    void genBlock(const BlockStmt* block) {
        if (!block) return;
        for (auto& s : block->stmts) genStmt(s.get());
    }

    void genStmt(const Stmt* s) {
        if (!s) return;
        switch (s->kind) {
            case Stmt::Kind::Let:      genLet(s);      break;
            case Stmt::Kind::Const:    genConst(s);    break;
            case Stmt::Kind::ExprStmt: genExprStmt(s); break;
            case Stmt::Kind::Return:   genReturn(s);   break;
            case Stmt::Kind::Break:    genBreak(s);    break;
            case Stmt::Kind::Continue: genContinue(s); break;
            case Stmt::Kind::If:       genIf(s);       break;
            case Stmt::Kind::While:    genWhile(s);    break;
            case Stmt::Kind::Loop:     genLoop(s);     break;
            case Stmt::Kind::ForC:     genForC(s);     break;
            case Stmt::Kind::ForIn:    genForIn(s);    break;
            case Stmt::Kind::Switch:   genSwitch(s);   break;
            case Stmt::Kind::Wait:     genWait(s);     break;
            case Stmt::Kind::FuncDecl:
                genFuncDecl(static_cast<const FuncDecl*>(s), "");
                break;
            case Stmt::Kind::Block: {
                line("{");
                indent();
                genBlock(static_cast<const BlockStmt*>(s));
                dedent();
                line("}");
                break;
            }
            default: break;
        }
    }

    void genLet(const Stmt* s) {
        auto* l = static_cast<const LetStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        if (!l->mut) write("const ");
        write(cppType(l->type) + " " + l->name + " = ");
        genExpr(l->init.get());
        write(";\n");
        // Track Scene variables for .add() dispatch
        if (l->type.base == "Scene")
            m_sceneVars.insert(l->name);
    }

    void genExprStmt(const Stmt* s) {
        auto* e = static_cast<const ExprStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        genExpr(e->expr.get());
        write(";\n");
    }

    void genReturn(const Stmt* s) {
        auto* r = static_cast<const ReturnStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("return");
        if (r->value) { write(" "); genExpr(r->value.get()); }
        write(";\n");
    }

    void genBreak(const Stmt* s) {
        auto* b = static_cast<const BreakStmt*>(s);
        if (!b->label.empty()) line("goto __break_" + b->label + ";");
        else                   line("break;");
    }

    void genContinue(const Stmt* s) {
        auto* c = static_cast<const ContinueStmt*>(s);
        if (!c->label.empty()) line("goto __continue_" + c->label + ";");
        else                   line("continue;");
    }

    void genIf(const Stmt* s) {
        auto* i = static_cast<const IfStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("if ("); genExpr(i->cond.get()); write(") {\n");
        indent(); genBlock(i->then_.get()); dedent();
        if (i->else_) {
            line("} else {");
            indent(); genBlock(i->else_.get()); dedent();
        }
        line("}");
    }

    void genWhile(const Stmt* s) {
        auto* w = static_cast<const WhileStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("while ("); genExpr(w->cond.get()); write(") {\n");
        indent(); genBlock(w->body.get()); dedent();
        line("}");
    }

    void genLoop(const Stmt* s) {
        auto* l = static_cast<const LoopStmt*>(s);
        line("while (true) {");
        indent(); genBlock(l->body.get()); dedent();
        line("}");
    }

    void genForC(const Stmt* s) {
        auto* f = static_cast<const ForCStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("for (" + cppType(f->type) + " " + f->var + " = ");
        genExpr(f->init.get());
        write("; "); genExpr(f->cond.get());
        write("; "); genExpr(f->step.get());
        write(") {\n");
        indent(); genBlock(f->body.get()); dedent();
        line("}");
    }

    // BUG-01: range expansion  BUG-05: primitive loop var  BUG-13/14: labels
    void genForIn(const Stmt* s) {
        auto* f = static_cast<const ForInStmt*>(s);
        write(std::string(m_indent * 4, ' '));

        if (f->iterable->kind == Expr::Kind::Range) {
            auto* r = static_cast<const RangeExpr*>(f->iterable.get());
            std::string t = cppType(f->type);
            write("for (" + t + " " + f->var + " = ");
            genExpr(r->from.get());
            write("; " + f->var + (r->inclusive ? " <= " : " < "));
            genExpr(r->to.get());
            write("; ++" + f->var + ") {\n");
        } else {
            std::string varDecl = isPrimitive(f->type)
                ? cppType(f->type) + " " + f->var
                : "const " + cppType(f->type) + "& " + f->var;
            write("for (" + varDecl + " : ");
            genExpr(f->iterable.get());
            write(") {\n");
        }

        indent(); genBlock(f->body.get()); dedent();
        line("}");

        if (!f->label.empty()) {
            line("__continue_" + f->label + ":;");
            line("__break_"    + f->label + ":;");
        }
    }

    void genSwitch(const Stmt* s) {
        auto* sw = static_cast<const SwitchStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("switch ("); genExpr(sw->expr.get()); write(") {\n");
        for (auto& c : sw->cases) {
            if (c.isDefault) {
                line("default:");
            } else {
                for (auto& v : c.values) {
                    write(std::string(m_indent * 4, ' '));
                    write("case "); genExpr(v.get()); write(":\n");
                }
            }
            indent();
            for (auto& b : c.body) genStmt(b.get());
            dedent();
        }
        line("}");
    }

    // BUG-02: clear stub comment
    void genWait(const Stmt* s) {
        auto* w = static_cast<const WaitStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("/* TODO(wait): requires VM scheduler -- duration = ");
        genExpr(w->duration.get());
        write(" */\n");
    }

    // -----------------------------------------------------------------------
    // Expressions
    // -----------------------------------------------------------------------
    void genExpr(const Expr* e) {
        if (!e) return;
        switch (e->kind) {
            case Expr::Kind::IntLit:
                write(std::to_string(static_cast<const IntLitExpr*>(e)->value));
                break;
            // BUG-07: emit raw source text to preserve precision
            case Expr::Kind::FloatLit: {
                auto* fl = static_cast<const FloatLitExpr*>(e);
                write(fl->rawValue.empty() ? std::to_string(fl->value) : fl->rawValue);
                break;
            }
            case Expr::Kind::BoolLit:
                write(static_cast<const BoolLitExpr*>(e)->value ? "true" : "false");
                break;
            case Expr::Kind::StrLit:
                write("\"" + static_cast<const StrLitExpr*>(e)->value + "\"");
                break;
            case Expr::Kind::NullLit:
            case Expr::Kind::NoneLit:
                write("std::nullopt");
                break;
            case Expr::Kind::Ident:
                genIdent(static_cast<const IdentExpr*>(e));
                break;
            case Expr::Kind::Unary:
                genUnary(static_cast<const UnaryExpr*>(e));
                break;
            case Expr::Kind::Binary:
                genBinary(static_cast<const BinaryExpr*>(e));
                break;
            case Expr::Kind::Assign:
                genAssign(static_cast<const AssignExpr*>(e));
                break;
            case Expr::Kind::Call:
                genCall(static_cast<const CallExpr*>(e));
                break;
            case Expr::Kind::Member:
            case Expr::Kind::SafeMember:
                genMember(static_cast<const MemberExpr*>(e));
                break;
            case Expr::Kind::Index:
                genIndex(static_cast<const IndexExpr*>(e));
                break;
            case Expr::Kind::Cast:
                genCast(static_cast<const CastExpr*>(e));
                break;
            case Expr::Kind::NullCoal:
                genNullCoal(static_cast<const NullCoalExpr*>(e));
                break;
            case Expr::Kind::ForceUnwrap:
                genExpr(static_cast<const ForceUnwrapExpr*>(e)->value.get());
                write(".value()");
                break;
            case Expr::Kind::Some_:
                genExpr(static_cast<const SomeExpr*>(e)->value.get());
                break;
            case Expr::Kind::ArrayLit:
                genArrayLit(static_cast<const ArrayLitExpr*>(e));
                break;
            case Expr::Kind::TupleLit:
                genTupleLit(static_cast<const TupleLitExpr*>(e));
                break;
            case Expr::Kind::StructInit:
                genStructInit(static_cast<const StructInitExpr*>(e));
                break;
            case Expr::Kind::Range:
                write("/* error: range outside for-in */");
                break;
            case Expr::Kind::Spawn:
                write("/* TODO(spawn): requires VM scheduler */ ");
                genExpr(static_cast<const SpawnExpr*>(e)->call.get());
                break;
            default:
                write("/* unknown expr */");
                break;
        }
    }

    void genIdent(const IdentExpr* e) {
        static const std::unordered_map<std::string,std::string> builtins = {
            {"MouseDown",       "IsMouseButtonDown"},
            {"MousePressed",    "IsMouseButtonPressed"},
            {"MouseReleased",   "IsMouseButtonReleased"},
            {"GetMouseX",       "GetMouseX"},
            {"GetMouseY",       "GetMouseY"},
            {"GetMouseDeltaX",  "GetMouseDeltaX"},
            {"GetMouseDeltaY",  "GetMouseDeltaY"},
            {"GetMouseScroll",  "GetMouseScroll"},
            {"GetDeltaTime",    "GetDeltaTime"},
            {"GetFPS",          "GetFPS"},
            {"GetTime",         "GetTime"},
            {"SetTimeScale",    "SetTimeScale"},
            {"DebugMode",       "DebugMode"},
            {"IsDebugMode",     "IsDebugMode"},
            {"Emit",            "Emit"},
            {"Connect",         "Connect"},
            {"GetNode",         "GetNode"},
            {"GetChild",        "GetChild"},
        };
        auto it = builtins.find(e->name);
        write(it != builtins.end() ? it->second : e->name);
    }

    void genUnary(const UnaryExpr* e) {
        if (e->postfix) { genExpr(e->operand.get()); write(e->op); }
        else            { write(e->op); genExpr(e->operand.get()); }
    }

    void genBinary(const BinaryExpr* e) {
        write("(");
        genExpr(e->left.get());
        write(" " + e->op + " ");
        genExpr(e->right.get());
        write(")");
    }

    void genAssign(const AssignExpr* e) {
        genExpr(e->target.get());
        write(" " + e->op + " ");
        genExpr(e->value.get());
    }

    void genCall(const CallExpr* e) {
        // ----------------------------------------------------------------
        // Member call special cases
        // ----------------------------------------------------------------
        if (e->callee->kind == Expr::Kind::Member) {
            auto* mem = static_cast<const MemberExpr*>(e->callee.get());

            // scene.add(TypeName, "name") -> scene.Add<TypeName>("name")
            // node.add(TypeName, "name")  -> node->AddChild<TypeName>("name")
            if (mem->member == "add"
                && e->args.size() == 2
                && e->args[0]->kind == Expr::Kind::Ident
                && e->args[1]->kind == Expr::Kind::StrLit)
            {
                auto* typeId  = static_cast<const IdentExpr*>(e->args[0].get());
                auto* nameLit = static_cast<const StrLitExpr*>(e->args[1].get());
                bool isScene  = false;
                if (mem->object->kind == Expr::Kind::Ident) {
                    auto* obj = static_cast<const IdentExpr*>(mem->object.get());
                    isScene = m_sceneVars.count(obj->name) > 0;
                }
                if (isScene) {
                    genExpr(mem->object.get());
                    write(".Add<" + typeId->name + ">(\"" + nameLit->value + "\")");
                } else {
                    genExpr(mem->object.get());
                    write("->AddChild<" + typeId->name + ">(\"" + nameLit->value + "\")");
                }
                return;
            }

            // scene.update(dt) -> scene.Update(dt)
            if (mem->member == "update" && e->args.size() == 1) {
                genExpr(mem->object.get());
                write(".Update("); genExpr(e->args[0].get()); write(")");
                return;
            }
            // scene.draw() -> scene.Draw()
            if (mem->member == "draw" && e->args.empty()) {
                genExpr(mem->object.get());
                write(".Draw()");
                return;
            }
            // scene.remove("name") -> scene.Remove("name")
            if (mem->member == "remove" && e->args.size() == 1) {
                genExpr(mem->object.get());
                write(".Remove("); genExpr(e->args[0].get()); write(")");
                return;
            }
            // scene.get("name") -> scene.GetNode("name")
            if (mem->member == "get" && e->args.size() == 1) {
                genExpr(mem->object.get());
                write(".GetNode("); genExpr(e->args[0].get()); write(")");
                return;
            }
        }

        // ----------------------------------------------------------------
        // Top-level function special cases
        // ----------------------------------------------------------------
        if (e->callee->kind == Expr::Kind::Ident) {
            auto* id = static_cast<const IdentExpr*>(e->callee.get());

            // Scene() -> Scene{}
            if (id->name == "Scene" && e->args.empty()) {
                write("Scene{}");
                return;
            }

            // BUG-04: Print -> printf
            if (id->name == "Print") {
                write("printf(");
                for (size_t i = 0; i < e->args.size(); i++) {
                    if (i > 0) write(", ");
                    genExpr(e->args[i].get());
                }
                write(")");
                return;
            }

            // ToString(x) -> std::to_string(x).c_str()
            if (id->name == "ToString" && e->args.size() == 1) {
                write("std::to_string(");
                genExpr(e->args[0].get());
                write(").c_str()");
                return;
            }

            // DrawText(text, x, y, r, g, b, a) -> DrawText(text, x, y, Color{...})
            if (id->name == "DrawText" && e->args.size() == 7) {
                write("DrawText(");
                genExpr(e->args[0].get()); write(", ");
                write("(float)"); genExpr(e->args[1].get()); write(", ");
                write("(float)"); genExpr(e->args[2].get()); write(", ");
                write("Color{(float)");
                genExpr(e->args[3].get()); write(", (float)");
                genExpr(e->args[4].get()); write(", (float)");
                genExpr(e->args[5].get()); write(", (float)");
                genExpr(e->args[6].get());
                write("})");
                return;
            }

            // Key input functions: cast arg to Key::Code
            static const std::unordered_map<std::string,std::string> keyFuncs = {
                {"KeyDown",      "IsKeyDown"},
                {"KeyPressed",   "IsKeyPressed"},
                {"KeyReleased",  "IsKeyReleased"},
                {"IsKeyDown",    "IsKeyDown"},
                {"IsKeyPressed", "IsKeyPressed"},
                {"IsKeyReleased","IsKeyReleased"},
            };
            auto kfit = keyFuncs.find(id->name);
            if (kfit != keyFuncs.end() && e->args.size() == 1) {
                bool alreadyKeyCode = false;
                if (e->args[0]->kind == Expr::Kind::Member) {
                    auto* m = static_cast<const MemberExpr*>(e->args[0].get());
                    if (m->object->kind == Expr::Kind::Ident) {
                        auto* mid = static_cast<const IdentExpr*>(m->object.get());
                        if (mid->name == "Key") alreadyKeyCode = true;
                    }
                }
                write(kfit->second + "(");
                if (!alreadyKeyCode) write("(Key::Code)");
                genExpr(e->args[0].get());
                write(")");
                return;
            }
        }

        // Generic call
        genExpr(e->callee.get());
        write("(");
        for (size_t i = 0; i < e->args.size(); i++) {
            if (i > 0) write(", ");
            genExpr(e->args[i].get());
        }
        write(")");
    }

    void genMember(const MemberExpr* e) {
        // Key.X / Mouse.X / Gamepad.X -> Key::X etc.
        if (e->object->kind == Expr::Kind::Ident) {
            auto* id = static_cast<const IdentExpr*>(e->object.get());
            static const std::unordered_set<std::string> cppNamespaces = {
                "Key", "Mouse", "Gamepad"
            };
            if (cppNamespaces.count(id->name)) {
                // Esc is canonical; Escape/ESC alias to it
                static const std::unordered_map<std::string,std::string> keyAliases = {
                    {"Escape",  "Esc"},
                    {"ESC",     "Esc"},
                    {"Return",  "Enter"},
                    {"Del",     "Delete"},
                    {"Ins",     "Insert"},
                    {"LShift",  "Shift"},
                    {"RShift",  "Shift"},
                    {"LCtrl",   "Ctrl"},
                    {"RCtrl",   "Ctrl"},
                };
                std::string member = e->member;
                if (id->name == "Key") {
                    auto it = keyAliases.find(member);
                    if (it != keyAliases.end()) member = it->second;
                }
                write(id->name + "::" + member);
                return;
            }
        }

        // BUG-06: safe member access on optional types
        if (e->safe) {
            write("[&]() -> auto { auto _ks_obj_ = ");
            genExpr(e->object.get());
            write("; return _ks_obj_ ? _ks_obj_->" + e->member + " : std::nullopt; }()");
            return;
        }

        genExpr(e->object.get());
        write(".");
        write(e->member);
    }

    void genIndex(const IndexExpr* e) {
        genExpr(e->object.get());
        write("["); genExpr(e->index.get()); write("]");
    }

    void genCast(const CastExpr* e) {
        write("static_cast<" + cppType(e->target) + ">(");
        genExpr(e->value.get());
        write(")");
    }

    void genNullCoal(const NullCoalExpr* e) {
        genExpr(e->left.get());
        write(".value_or(");
        genExpr(e->right.get());
        write(")");
    }

    void genArrayLit(const ArrayLitExpr* e) {
        write("{");
        for (size_t i = 0; i < e->elements.size(); i++) {
            if (i > 0) write(", ");
            genExpr(e->elements[i].get());
        }
        write("}");
    }

    void genTupleLit(const TupleLitExpr* e) {
        write("std::make_tuple(");
        for (size_t i = 0; i < e->elements.size(); i++) {
            if (i > 0) write(", ");
            genExpr(e->elements[i].get());
        }
        write(")");
    }

    void genStructInit(const StructInitExpr* e) {
        write(e->typeName + "{");
        for (size_t i = 0; i < e->fields.size(); i++) {
            if (i > 0) write(", ");
            write("." + e->fields[i].name + " = ");
            genExpr(e->fields[i].value.get());
        }
        write("}");
    }
};

} // namespace KonScript
