#pragma once
// -----------------------------------------------------------------------
// KonScript C++ Code Generator
// Walks the AST and emits C++ that links against KonEngine.
// -----------------------------------------------------------------------
#include "ast.hpp"
#include <string>
#include <sstream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <vector>
#include <unordered_set>
#include <unordered_map>

namespace KonScript {

class Codegen {
public:
    struct Error {
        std::string message;
        int line, col;
    };

    const std::vector<Error>& errors() const { return m_errors; }
    bool hasErrors() const { return !m_errors.empty(); }

    enum class Target {
        Engine,     // links against KonEngine, node types available
        Standalone, // plain C++ stdlib only
    };

    void setTarget(Target t) { m_target = t; }
    Target target() const    { return m_target; }

    // When true: rewrite #include "foo.ks" → #include "foo.ks.cpp" (cmake --cpp mode)
    // When false: skip .ks includes entirely (konscript unity build handles them)
    void setRewriteKsIncludes(bool v) { m_rewriteKsIncludes = v; }

    // Pre-register struct/class/enum names from an included .ks file so that
    // cppBaseType() treats them as value types, not unknown pointers.
    void addIncludeTypes(const Program& inc) {
        for (auto& s : inc.stmts) {
            if (s->kind == Stmt::Kind::StructDecl)
                m_structNames.insert(static_cast<const StructDecl*>(s.get())->name);
            else if (s->kind == Stmt::Kind::ClassDecl)
                m_classNames.insert(static_cast<const ClassDecl*>(s.get())->name);
            else if (s->kind == Stmt::Kind::EnumDecl) {
                auto* e = static_cast<const EnumDecl*>(s.get());
                m_enumNames.insert(e->name);
                for (auto& v : e->variants)
                    m_enumVariants[v.name] = e->name;
            } else if (s->kind == Stmt::Kind::NodeDecl)
                m_userNodeTypes.insert(static_cast<const NodeDecl*>(s.get())->name);
        }
    }

    std::string generate(const Program& prog) {
        m_out.str("");
        m_indent = 0;
        m_ptrVars.clear();
        m_varTypes.clear();
        m_typeParams.clear();
        m_intelAsm = prog.intelAsm;
        // NOTE: do NOT clear m_structNames / m_classNames / m_enumNames /
        // m_enumVariants / m_userNodeTypes here. They may be pre-populated by
        // addIncludeTypes() before generate() is called. They accumulate within
        // this Codegen instance (create a fresh instance per file).
        m_emittedEnums.clear();

        line("// Generated by KonScript v0.1.0 -- do not edit");
        line("// Source: " + prog.filename);

        if (m_target == Target::Engine) {
            line("#include \"KonEngine.hpp\"");
            line("#include <cstdio>");
            line("#include <cmath>");
        }
        line("#include <string>");
        line("#include <vector>");
        line("#include <functional>");
        line("#include <iostream>");
        line("#include <sstream>");
        line("#include <optional>");
        line("#include <fstream>");
        line("#include <unordered_map>");
        line("#include <algorithm>");
        // Always include functional for std::function (closures)
        line("#include <functional>");
        if (m_target == Target::Standalone) {
            line("#include <cstdint>");
            line("#include <tuple>");
            line("#include <cmath>");
        }

        // _KsResult<T> and all _ks_* helpers wrapped in a guard
        // so the unity build only defines them once.
        line("#ifndef _KS_STDLIB_HELPERS_DEFINED");
        line("#define _KS_STDLIB_HELPERS_DEFINED");
        line("template<typename T>");
        line("struct _KsResult {");
        line("    bool        ok    = false;");
        line("    T           value = {};");
        line("    std::string error;");
        line("    static _KsResult<T> Ok(T v) { _KsResult<T> r; r.ok=true;  r.value=std::move(v); return r; }");
        line("    static _KsResult<T> Err(const std::string& e) { _KsResult<T> r; r.ok=false; r.error=e; return r; }");
        line("};");

        // File I/O helpers
        line("inline _KsResult<std::string> _ks_file_read(const std::string& p){");
        line("    std::ifstream f(p);if(!f)return _KsResult<std::string>::Err(\"cannot open: \"+p);");
        line("    std::ostringstream ss;ss<<f.rdbuf();return _KsResult<std::string>::Ok(ss.str());}");
        line("inline _KsResult<std::string> _ks_file_write(const std::string& p,const std::string& c){");
        line("    std::ofstream f(p,std::ios::trunc);if(!f)return _KsResult<std::string>::Err(\"cannot write: \"+p);");
        line("    f<<c;return _KsResult<std::string>::Ok(\"\");}");
        line("inline _KsResult<std::string> _ks_file_append(const std::string& p,const std::string& c){");
        line("    std::ofstream f(p,std::ios::app);if(!f)return _KsResult<std::string>::Err(\"cannot append: \"+p);");
        line("    f<<c;return _KsResult<std::string>::Ok(\"\");}");
        line("inline bool _ks_file_exists(const std::string& p){std::ifstream f(p);return f.good();}");
        line("inline _KsResult<std::string> _ks_file_delete(const std::string& p){");
        line("    return std::remove(p.c_str())==0?_KsResult<std::string>::Ok(\"\")");
        line("        :_KsResult<std::string>::Err(\"cannot delete: \"+p);}");
        line("inline _KsResult<std::vector<std::string>> _ks_file_lines(const std::string& p){");
        line("    std::ifstream f(p);if(!f)return _KsResult<std::vector<std::string>>::Err(\"cannot open: \"+p);");
        line("    std::vector<std::string> out;std::string l;");
        line("    while(std::getline(f,l))out.push_back(l);");
        line("    return _KsResult<std::vector<std::string>>::Ok(out);}");

        // String helpers
        line("inline int _ks_str_len(const std::string& s){return(int)s.size();}");
        line("inline std::vector<std::string> _ks_str_split(const std::string& s,const std::string& d){");
        line("    std::vector<std::string> r;size_t p=0,f;");
        line("    while((f=s.find(d,p))!=std::string::npos){r.push_back(s.substr(p,f-p));p=f+d.size();}");
        line("    r.push_back(s.substr(p));return r;}");
        line("inline std::string _ks_str_trim(const std::string& s){");
        line("    auto l=s.find_first_not_of(\" \\t\\n\\r\");auto r=s.find_last_not_of(\" \\t\\n\\r\");");
        line("    return l==std::string::npos?\"\":s.substr(l,r-l+1);}");
        line("inline bool _ks_str_contains(const std::string& s,const std::string& sub){return s.find(sub)!=std::string::npos;}");
        line("inline std::string _ks_str_replace(const std::string& s,const std::string& f,const std::string& t){");
        line("    std::string r=s;size_t p=0;");
        line("    while((p=r.find(f,p))!=std::string::npos){r.replace(p,f.size(),t);p+=t.size();}return r;}");
        line("inline bool _ks_str_starts(const std::string& s,const std::string& p){return s.rfind(p,0)==0;}");
        line("inline bool _ks_str_ends(const std::string& s,const std::string& e){");
        line("    return s.size()>=e.size()&&s.compare(s.size()-e.size(),e.size(),e)==0;}");
        line("inline std::string _ks_str_upper(std::string s){for(auto&c:s)c=toupper(c);return s;}");
        line("inline std::string _ks_str_lower(std::string s){for(auto&c:s)c=tolower(c);return s;}");
        line("inline std::string _ks_str_substr(const std::string& s,int p,int l){return s.substr(p,l);}");
        line("inline int _ks_str_toInt(const std::string& s){return std::stoi(s);}");
        line("inline float _ks_str_toFloat(const std::string& s){return std::stof(s);}");
        line("inline bool _ks_str_isEmpty(const std::string& s){return s.empty();}");
        // _ks_has: works on vector (std::find) and unordered_map (.count)
        line("template<typename C,typename V> inline bool _ks_has(const C& c,const V& v){return std::find(c.begin(),c.end(),v)!=c.end();}");
        line("template<typename K,typename MV,typename Q> inline bool _ks_has(const std::unordered_map<K,MV>& m,const Q& k){return m.count(K(k))>0;}");
        line("#endif // _KS_STDLIB_HELPERS_DEFINED");
        line("");
        line("#ifndef _KS_CORO_DEFINED");
        line("#define _KS_CORO_DEFINED");
        line("#if __cplusplus >= 202002L");
        line("#include <coroutine>");
        line("struct _KsTask { struct promise_type {");
        line("    float _w=0.f;");
        line("    _KsTask get_return_object(){return{std::coroutine_handle<promise_type>::from_promise(*this)};}");
        line("    std::suspend_never  initial_suspend()noexcept{return{};}") ;
        line("    std::suspend_always final_suspend()  noexcept{return{};}") ;
        line("    void return_void(){} void unhandled_exception(){}");
        line("    std::suspend_always yield_value(float s){_w=s;return{};}") ;
        line("};");
        line("std::coroutine_handle<promise_type> handle;");
        line("bool  done()    const{return !handle||handle.done();}");
        line("float waitTime()     {return handle.promise()._w;}");
        line("};");
        line("struct _KsScheduler{");
        line("    struct E{_KsTask t;float r=0.f;};");
        line("    std::vector<E> q;");
        line("    void spawn(_KsTask t){q.push_back({std::move(t),0.f});}");
        line("    void update(float dt){");
        line("        for(auto&e:q){if(e.t.done())continue;");
        line("            e.r-=dt;if(e.r>0.f)continue;");
        line("            e.t.handle.resume();");
        line("            if(!e.t.done())e.r=e.t.waitTime();}");
        line("        q.erase(std::remove_if(q.begin(),q.end(),[](const E&e){return e.t.done();}),q.end());}");
        line("};");
        line("inline _KsScheduler _ks_sched;");
        line("inline void _ks_spawn(_KsTask t){_ks_sched.spawn(std::move(t));}");
        line("#else");
        line("// C++17 stubs — coroutines require C++20 (-std=c++20)");
        line("struct _KsTask {};");
        line("struct _KsScheduler { void update(float){} void spawn(_KsTask){} };");
        line("inline _KsScheduler _ks_sched;");
        line("inline void _ks_spawn(_KsTask){}");
        line("#endif // C++20");
        line("#endif // _KS_CORO_DEFINED");
        line("");
        // Emit #pragma once for module files (included by others),
        // but NOT for entry files that have a main() — they're .cpp not headers.
        // Detect whether this file has a main() function.
        // Entry files (has main): compiled as .cpp — no #pragma once, gets _KSInit.
        // Module files (no main): included by others — needs #pragma once, no _KSInit.
        bool isEntryFile = false;
        for (auto& s : prog.stmts) {
            if (s->kind == Stmt::Kind::FuncDecl) {
                auto* fd = static_cast<const FuncDecl*>(s.get());
                if (fd->name == "main") { isEntryFile = true; break; }
            }
        }

        if (!isEntryFile) {
            // Module file: guard against multiple inclusion
            line("#pragma once");
        } else {
            // Entry file: one-time init — boolalpha + unitbuf
            // unitbuf forces flush after every output operation so Print()
            // shows immediately in the editor's Output tab (piped subprocess).
            line("namespace { struct _KSInit {");
            line("    _KSInit() { std::cout << std::boolalpha << std::unitbuf; }");
            line("} _ks_init; }");
        }

        line("");

        // Emit includes first so forward declarations can see cross-file types
        for (auto& s : prog.stmts)
            if (s->kind == Stmt::Kind::Include)
                genInclude(s.get());

        // Forward declarations pass — also populates m_userNodeTypes
        for (auto& s : prog.stmts)
            if (s->kind == Stmt::Kind::NodeDecl   ||
                s->kind == Stmt::Kind::StructDecl  ||
                s->kind == Stmt::Kind::ClassDecl   ||
                s->kind == Stmt::Kind::EnumDecl    ||
                s->kind == Stmt::Kind::FuncDecl    ||
                s->kind == Stmt::Kind::ExternDecl ||
                s->kind == Stmt::Kind::InterfaceDecl)
                forwardDeclare(s.get());

        line("");

        // Emit everything except includes (already done above)
        for (auto& s : prog.stmts)
            if (s->kind != Stmt::Kind::Include)
                genTopLevel(s.get());

        return m_out.str();
    }

private:
    std::ostringstream m_out;
    int                m_indent = 0;
    Target             m_target = Target::Standalone;
    bool               m_rewriteKsIncludes = false;
    std::vector<Error> m_errors;
    std::unordered_set<std::string> m_enumNames;
    std::unordered_set<std::string> m_interfaceNames;
    std::unordered_set<std::string> m_currentClassIfaces;
    // Maps enum variant name → enum type name, for switch case qualification
    std::unordered_map<std::string, std::string> m_enumVariants;
    // User-declared struct names — value types, not pointers
    std::unordered_set<std::string> m_structNames;
    // User-declared class names — also value types (not pointers)
    std::unordered_set<std::string> m_classNames;
    // Maps local variable name → its base type name, for method dispatch
    std::unordered_map<std::string, std::string> m_varTypes;
    std::unordered_set<std::string> m_typeParams;
    bool m_intelAsm = false;
    // Enums emitted early in forwardDeclare — skip in genTopLevel
    std::unordered_set<std::string> m_emittedEnums;

    // User-declared node types (populated during forward declarations)
    std::unordered_set<std::string> m_userNodeTypes;

    // Local variables that are pointer types (populated during genLet)
    std::unordered_set<std::string> m_ptrVars;

    // Engine types that are plain value types, NOT pointers
    const std::unordered_set<std::string> m_engineValueTypes = {
        "Camera2D", "Sound", "Music", "Texture", "Scene"
    };

    void error(const std::string& msg, int l = 0, int c = 0) {
        m_errors.push_back({msg, l, c});
    }

    // -----------------------------------------------------------------------
    // Output helpers
    // -----------------------------------------------------------------------
    void write(const std::string& s) { m_out << s; }
    void line(const std::string& s = "") {
        m_out << std::string(m_indent * 4, ' ') << s << "\n";
    }
    void indent()   { m_indent++; }
    void dedent()   { if (m_indent > 0) m_indent--; }

    // -----------------------------------------------------------------------
    // Type conversion
    // -----------------------------------------------------------------------
    std::string cppType(const TypeAnnotation& ta) {
        if (ta.isPtr) {
            TypeAnnotation inner=ta; inner.isPtr=false; inner.isPtrMut=false;
            return ta.isPtrMut ? (cppType(inner)+"*") : ("const "+cppType(inner)+"*");
        }
        if (ta.isFuncType) {
            std::string ret = ta.funcReturnType ? cppType(*ta.funcReturnType) : "void";
            std::string sig = "std::function<" + ret + "(";
            for (size_t i = 0; i < ta.funcParamTypes.size(); i++) {
                if (i > 0) sig += ", ";
                sig += cppType(ta.funcParamTypes[i]);
            }
            sig += ")>";
            if (ta.nullable) return "std::optional<" + sig + ">";
            return sig;
        }
        if (ta.isTuple) {
            std::string s = "std::tuple<";
            for (size_t i = 0; i < ta.tupleTypes.size(); i++) {
                if (i > 0) s += ", ";
                s += cppType(ta.tupleTypes[i]);
            }
            return s + ">";
        }
        if (ta.isArray) {
            TypeAnnotation inner; inner.base = ta.base;
            inner.typeParams = ta.typeParams;
            std::string elem = cppType(inner);
            if (ta.arraySize >= 0)
                return "std::array<" + elem + ", " +
                       std::to_string(ta.arraySize) + ">";
            return "std::vector<" + elem + ">";
        }
        if (!ta.typeParams.empty() && ta.base != "Result" && ta.base != "HashMap") {
            std::string s = ta.base + "<";
            for (size_t i = 0; i < ta.typeParams.size(); i++) {
                if (i) s += ", "; s += cppType(ta.typeParams[i]);
            }
            s += ">";
            if (ta.nullable) return "std::optional<" + s + ">";
            return s;
        }
        // Result<T> → _KsResult<T>
        if (ta.base == "Result") {
            std::string inner = ta.typeParams.empty() ? "std::string" : cppType(ta.typeParams[0]);
            return "_KsResult<" + inner + ">";
        }
        // HashMap<K,V> → std::unordered_map<K,V>
        if (ta.base == "HashMap") {
            std::string k = ta.typeParams.empty() ? "std::string" : cppType(ta.typeParams[0]);
            std::string v = ta.typeParams.size() < 2 ? "std::string" : cppType(ta.typeParams[1]);
            return "std::unordered_map<" + k + ", " + v + ">";
        }
        std::string base = cppBaseType(ta.base);
        if (ta.nullable) return "std::optional<" + base + ">";
        return base;
    }

    std::string cppBaseType(const std::string& name) {
        if (name == "I8")     return "int8_t";
        if (name == "I16")    return "int16_t";
        if (name == "I32")    return "int32_t";
        if (name == "I64")    return "int64_t";
        if (name == "U8")     return "uint8_t";
        if (name == "U16")    return "uint16_t";
        if (name == "U32")    return "uint32_t";
        if (name == "U64")    return "uint64_t";
        if (name == "F32")    return "float";
        if (name == "F64")    return "float"; // engine uses float throughout
        if (name == "Bool")   return "bool";
        // str/Str → std::string (used as value type in templates, arrays, etc.)
        // Note: as a local variable type we keep std::string too for consistency
        if (name == "str" || name == "Str") return "std::string";
        if (name == "String") return "std::string";
        if (name == "Vec2")   return "Vector2";
        if (name == "Color")  return "Color";
        if (name == "void")   return "void";

        // Engine value types -- NOT pointers
        if (m_engineValueTypes.count(name)) return name;

        // Built-in engine node types -- become pointers
        static const std::unordered_set<std::string> builtinNodeTypes = {
            "Node", "Node2D", "Sprite2D", "Collider2D", "AnimationPlayer"
        };
        if (builtinNodeTypes.count(name)) return name + "*";

        // User-declared node types -- also become pointers
        if (m_userNodeTypes.count(name)) return name + "*";

        if (m_typeParams.count(name)) return name;
        // Enum types are value types (enum class in C++) — NOT pointers.
        if (m_enumNames.count(name)) return name;

        // User-declared struct and class types are value types — NOT pointers.
        if (m_structNames.count(name)) return name;
        if (m_classNames.count(name))  return name;

        // Unknown type — assume it's a user node from another file (pointer).
        // Primitive types, engine types, and value types are all handled above,
        // so anything reaching here is treated as a class/node type.
        return name + "*";
    }

    // Returns true if a type name produces a pointer in C++
    bool isPointerType(const std::string& name) {
        static const std::unordered_set<std::string> builtinNodeTypes = {
            "Node", "Node2D", "Sprite2D", "Collider2D", "AnimationPlayer"
        };
        return builtinNodeTypes.count(name) || m_userNodeTypes.count(name);
    }

    // -----------------------------------------------------------------------
    // Forward declarations
    // -----------------------------------------------------------------------
    void forwardDeclare(const Stmt* s) {
        switch (s->kind) {
            case Stmt::Kind::FuncDecl: {
                auto* f = static_cast<const FuncDecl*>(s);
                if (f->name == "main") break;
                if (!f->typeParams.empty()) {
                    std::string tpl = "template<";
                    for (size_t i = 0; i < f->typeParams.size(); i++) {
                        if (i) tpl += ", "; tpl += "typename " + f->typeParams[i];
                        m_typeParams.insert(f->typeParams[i]);
                    }
                    line(tpl + ">");
                }
                std::string ret;
                if (f->isCoroutine) ret = "_KsTask";
                else ret = f->returnType ? cppType(*f->returnType) : "void";
                std::string sig = ret + " " + f->name + "(";
                for (size_t i = 0; i < f->params.size(); i++) {
                    if (i) sig += ", ";
                    sig += cppType(f->params[i].type) + " " + f->params[i].name;
                }
                sig += ");";
                line(sig);
                for (auto& tp : f->typeParams) m_typeParams.erase(tp);
                break;
            }
            case Stmt::Kind::InterfaceDecl: {
                auto* id = static_cast<const InterfaceDecl*>(s);
                m_interfaceNames.insert(id->name);
                line("struct " + id->name + ";");
                break;
            }
            case Stmt::Kind::ExternDecl:
                genExtern(s);
                break;
            case Stmt::Kind::StructDecl: {
                auto* sd = static_cast<const StructDecl*>(s);
                m_structNames.insert(sd->name);
                if (!sd->typeParams.empty()) {
                    std::string tpl = "template<";
                    for (size_t i = 0; i < sd->typeParams.size(); i++) {
                        if (i) tpl += ", "; tpl += "typename " + sd->typeParams[i];
                    }
                    line(tpl + ">");
                }
                line("struct " + sd->name + ";");
                break;
            }
            case Stmt::Kind::ClassDecl: {
                auto* cd = static_cast<const ClassDecl*>(s);
                m_classNames.insert(cd->name);
                if (!cd->typeParams.empty()) {
                    std::string tpl = "template<";
                    for (size_t i = 0; i < cd->typeParams.size(); i++) {
                        if (i) tpl += ", "; tpl += "typename " + cd->typeParams[i];
                    }
                    line(tpl + ">");
                }
                line("class " + cd->name + ";");
                break;
            }
            case Stmt::Kind::NodeDecl: {
                auto* nd = static_cast<const NodeDecl*>(s);
                line("class " + nd->name + ";");
                m_userNodeTypes.insert(nd->name); // track for pointer logic
                break;
            }
            case Stmt::Kind::EnumDecl: {
                // Emit enum definition here (before function forward decls)
                // so that function signatures referencing enum types resolve.
                auto* ed = static_cast<const EnumDecl*>(s);
                m_enumNames.insert(ed->name);
                for (auto& v : ed->variants)
                    m_enumVariants[v.name] = ed->name;
                genEnum(s);
                m_emittedEnums.insert(ed->name);
                break;
            }
            default:
                break;
        }
    }

    // -----------------------------------------------------------------------
    // Top-level generation
    // -----------------------------------------------------------------------
    void genTopLevel(const Stmt* s) {
        switch (s->kind) {
            case Stmt::Kind::Include:    genInclude(s);   break;
            case Stmt::Kind::Const:      genConst(s);     break;
            case Stmt::Kind::EnumDecl:
                // Already emitted in forwardDeclare pass — skip
                if (!m_emittedEnums.count(static_cast<const EnumDecl*>(s)->name))
                    genEnum(s);
                break;
            case Stmt::Kind::StructDecl: genStruct(s);    break;
            case Stmt::Kind::ClassDecl:  genClass(s);     break;
            case Stmt::Kind::NodeDecl:   genNode(s);      break;
            case Stmt::Kind::FuncDecl:
                genFuncDecl(static_cast<const FuncDecl*>(s), "");
                break;
            case Stmt::Kind::Let:        genLet(s);       break;
            case Stmt::Kind::ExternDecl:    break;
            case Stmt::Kind::AsmStmt:       genAsmStmt(s);      break;
            case Stmt::Kind::InterfaceDecl: genInterface(s);     break;
            default: break;
        }
    }

    void genInclude(const Stmt* s) {
        auto* i = static_cast<const IncludeStmt*>(s);
        if (i->path == "engine") return; // already included at top
        if (!i->isSystem && i->path.size() > 3 && i->path.substr(i->path.size()-3) == ".ks") {
            if (m_rewriteKsIncludes)
                // cmake --cpp mode: rewrite player.ks → player.ks.cpp
                line("#include \"" + i->path + ".cpp\"");
            // else: unity build — skip, pipeline handles it
            return;
        }
        if (i->isSystem) {
            line("#include <" + i->path + ">");
        } else {
            line("#include \"" + i->path + "\"");
        }
    }

    void genConst(const Stmt* s) {
        auto* c = static_cast<const ConstStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        if (m_indent == 0) {
            // Only primitive types can be constexpr; std::string cannot.
            static const std::unordered_set<std::string> literalTypes = {
                "I8","I16","I32","I64","U8","U16","U32","U64",
                "F32","F64","Bool"
            };
            if (literalTypes.count(c->type.base)) write("constexpr ");
            else                                   write("inline const ");
        } else {
            write("const ");
        }
        write(cppType(c->type) + " " + c->name + " = ");
        genExpr(c->init.get());
        write(";\n");
    }

    // -----------------------------------------------------------------------
    // Enum
    // -----------------------------------------------------------------------
    void genEnum(const Stmt* s) {
        auto* e = static_cast<const EnumDecl*>(s);
        // Simple enum -- no payloads
        bool simple = true;
        for (auto& v : e->variants) if (v.payload) { simple = false; break; }

        if (simple) {
            line("enum class " + e->name + " {");
            indent();
            for (auto& v : e->variants) line(v.name + ",");
            dedent();
            line("};");
        } else {
            // Tagged union via struct
            line("struct " + e->name + " {");
            indent();
            line("enum class Tag {");
            indent();
            for (auto& v : e->variants) line(v.name + ",");
            dedent();
            line("} tag;");

            // Payload union
            line("union {");
            indent();
            for (auto& v : e->variants) {
                if (v.payload)
                    line(cppType(*v.payload) + " " + v.name + "_val;");
            }
            dedent();
            line("};");

            // Constructor helpers — build the struct inline, no external type needed
            for (auto& v : e->variants) {
                if (v.payload) {
                    write(std::string(m_indent * 4, ' '));
                    write("static " + e->name + " " + v.name + "(" +
                          cppType(*v.payload) + " val) {"
                          " " + e->name + " _s; _s.tag = Tag::" + v.name +
                          "; _s." + v.name + "_val = val; return _s; }\n");
                } else {
                    write(std::string(m_indent * 4, ' '));
                    write("static " + e->name + " " + v.name +
                          "() { " + e->name + " _s; _s.tag = Tag::" +
                          v.name + "; return _s; }\n");
                }
            }
            dedent();
            line("};");
        }
        line("");
    }

    // -----------------------------------------------------------------------
    // Struct
    // -----------------------------------------------------------------------
    void genStruct(const Stmt* s) {
        auto* st = static_cast<const StructDecl*>(s);
        std::string sattr;
        for(auto& a:st->attributes){
            if(a=="packed") sattr+=" __attribute__((packed))";
            else if(a.rfind("align",0)==0) sattr+=" "+a;
        }
        if (!st->typeParams.empty()) {
            std::string tpl = "template<";
            for (size_t i = 0; i < st->typeParams.size(); i++) {
                if (i) tpl += ", "; tpl += "typename " + st->typeParams[i];
                m_typeParams.insert(st->typeParams[i]);
            }
            line(tpl + ">");
        }
        line("struct " + st->name + sattr + " {");
        indent();
        for (auto& f : st->fields) {
            write(std::string(m_indent * 4, ' '));
            write(cppType(f.type) + " " + f.name);
            if (f.init) { write(" = "); genExpr(f.init.get()); }
            write(";\n");
        }
        dedent();
        line("};");
        line("");
    }

    // -----------------------------------------------------------------------
    // Class
    // -----------------------------------------------------------------------
    void genClass(const Stmt* s) {
        auto* c = static_cast<const ClassDecl*>(s);
        m_currentClassIfaces = std::unordered_set<std::string>(
            c->implements.begin(), c->implements.end());
        if (!c->typeParams.empty()) {
            std::string tpl = "template<";
            for (size_t i = 0; i < c->typeParams.size(); i++) {
                if (i) tpl += ", "; tpl += "typename " + c->typeParams[i];
                m_typeParams.insert(c->typeParams[i]);
            }
            line(tpl + ">");
        }
        // Build inheritance list: base class + interfaces
        // NOTE: do NOT include <T> in class name — that's for specializations only
        std::string decl = "class " + c->name;
        std::string inh;
        if (!c->base.empty()) inh += "public " + c->base;
        for (auto& iface : c->implements) {
            if (!inh.empty()) inh += ", ";
            inh += "public " + iface;
        }
        if (!inh.empty()) decl += " : " + inh;
        line(decl + " {");
        line("public:");
        indent();
        for (auto& f : c->fields) {
            write(std::string(m_indent * 4, ' '));
            write(cppType(f.type) + " " + f.name);
            if (f.init) { write(" = "); genExpr(f.init.get()); }
            write(";\n");
        }
        if (!c->fields.empty()) line("");
        for (auto& m : c->methods) genFuncDecl(m.get(), ""); // empty prefix: inline class body
        m_currentClassIfaces.clear();
        dedent();
        line("};");
        line("");
    }

    // -----------------------------------------------------------------------
    // Node
    // -----------------------------------------------------------------------
    // Returns true if an expression is safe as a C++ inline member initializer.
    // Calls (LoadSound, AddChild, this.add...) require runtime context so are NOT safe.
    bool isTrivialInit(const Expr* e) const {
        if (!e) return true;
        switch (e->kind) {
            case Expr::Kind::IntLit:
            case Expr::Kind::FloatLit:
            case Expr::Kind::BoolLit:
            case Expr::Kind::StrLit:
            case Expr::Kind::NullLit:
            case Expr::Kind::NoneLit:
            case Expr::Kind::Ident:    // constants, color presets etc.
                return true;
            case Expr::Kind::Unary: {
                auto* u = static_cast<const UnaryExpr*>(e);
                return isTrivialInit(u->operand.get());
            }
            case Expr::Kind::Binary: {
                auto* b = static_cast<const BinaryExpr*>(e);
                return isTrivialInit(b->left.get()) && isTrivialInit(b->right.get());
            }
            // Any call, member call, or member access on non-namespace is non-trivial
            case Expr::Kind::Call:
            case Expr::Kind::Member:
            case Expr::Kind::SafeMember:
            default:
                return false;
        }
    }

    void genNode(const Stmt* s) {
        auto* n = static_cast<const NodeDecl*>(s);
        if (m_target == Target::Standalone)
            line("class " + n->name + " {");
        else
            line("class " + n->name + " : public " + n->base + " {");
        line("public:");
        indent();

        // Collect fields whose initializers need to run in the constructor
        // (e.g. AddChild, LoadSound -- anything that isn't a literal/constant)
        std::vector<const FieldDecl*> ctorInits;
        for (auto& f : n->fields)
            if (f.init && !isTrivialInit(f.init.get()))
                ctorInits.push_back(&f);

        // Pre-populate m_ptrVars with all pointer-typed fields BEFORE emitting
        // the constructor body — otherwise nested field.add() calls don't know
        // that e.g. "player_node" is a pointer and emit .Add<> instead of ->AddChild<>.
        std::vector<std::string> addedFieldPtrs;
        for (auto& f : n->fields) {
            std::string ct = cppType(f.type);
            bool isPtr   = !ct.empty() && ct.back() == '*';
            bool isUNode = m_userNodeTypes.count(f.type.base) > 0;
            if (isPtr || isUNode) {
                m_ptrVars.insert(f.name);
                addedFieldPtrs.push_back(f.name);
            }
        }

        // Constructor
        if (m_target == Target::Engine) {
            write(std::string(m_indent * 4, ' '));
            write(n->name + "(const std::string& _name) : " + n->base + "(_name)");
            if (ctorInits.empty()) {
                write(" {}\n");
            } else {
                write(" {\n");
                indent();
                for (auto* f : ctorInits) {
                    write(std::string(m_indent * 4, ' '));
                    write(f->name + " = ");
                    genExpr(f->init.get());
                    write(";\n");
                }
                dedent();
                line("}");
            }
        } else {
            if (ctorInits.empty()) {
                line(n->name + "() {}");
            } else {
                line(n->name + "() {");
                indent();
                for (auto* f : ctorInits) {
                    write(std::string(m_indent * 4, ' '));
                    write(f->name + " = ");
                    genExpr(f->init.get());
                    write(";\n");
                }
                dedent();
                line("}");
            }
        }
        line("");

        // Fields -- trivial inits stay inline, non-trivial just declared (set in ctor)
        for (auto& f : n->fields) {
            write(std::string(m_indent * 4, ' '));
            write(cppType(f.type) + " " + f.name);
            if (f.init && isTrivialInit(f.init.get())) {
                write(" = ");
                genExpr(f.init.get());
            }
            write(";\n");
        }
        if (!n->fields.empty()) line("");

        for (auto& m : n->methods)
            genNodeMethod(m.get(), n->name);

        // Remove field ptrs so they don't leak to other nodes/methods
        for (auto& name : addedFieldPtrs)
            m_ptrVars.erase(name);

        dedent();
        line("};");
        line("");
    }

    void genNodeMethod(const FuncDecl* f, const std::string&) {
        struct MethodMap { std::string ks, sig; };
        static const std::vector<MethodMap> builtinMethods = {
            {"Ready",            "void Ready() override"},
            {"Update",           "void Update(float dt) override"},
            {"Draw",             "void Draw() override"},
            {"OnCollisionEnter", "void OnCollisionEnter(Collider2D* other) override"},
            {"OnCollisionExit",  "void OnCollisionExit(Collider2D* other) override"},
        };
        for (auto& bm : builtinMethods) {
            if (f->name == bm.ks) {
                line(bm.sig + " {");
                indent();
                // Register pointer params so genMember uses -> inside the body.
                // OnCollisionEnter/Exit take Collider2D* other — must use ->.
                // Update takes float dt — not a pointer, harmless to skip.
                std::unordered_set<std::string> addedParams;
                for (auto& p : f->params) {
                    std::string ct = cppType(p.type);
                    bool isPtr = !ct.empty() && ct.back() == '*';
                    bool isNode = m_userNodeTypes.count(p.type.base) > 0;
                    static const std::unordered_set<std::string> builtinNodes = {
                        "Node","Node2D","Sprite2D","Collider2D","AnimationPlayer"
                    };
                    if (isPtr || isNode || builtinNodes.count(p.type.base)) {
                        m_ptrVars.insert(p.name);
                        addedParams.insert(p.name);
                    }
                }
                // Also handle hardcoded "other: Collider2D" param by name
                if (f->name == "OnCollisionEnter" || f->name == "OnCollisionExit") {
                    m_ptrVars.insert("other");
                    addedParams.insert("other");
                }
                genBlock(f->body.get());
                // Clean up — don't leak param names into outer scope
                for (auto& p : addedParams) m_ptrVars.erase(p);
                dedent();
                line("}");
                line("");
                return;
            }
        }
        genFuncDecl(f, "");
    }

    // -----------------------------------------------------------------------
    // Function declaration
    // -----------------------------------------------------------------------
    // Check if a method name is in any implemented interface
    bool isOverride(const std::string& methodName) {
        for (auto& iface : m_currentClassIfaces) {
            (void)iface; // interface method names tracked separately
        }
        return !m_currentClassIfaces.empty(); // simple: all methods override if class implements
    }

    void genFuncDecl(const FuncDecl* f, const std::string& prefix) {
        if (!f->typeParams.empty()) {
            std::string tpl = "template<";
            for (size_t i = 0; i < f->typeParams.size(); i++) {
                if (i) tpl += ", "; tpl += "typename " + f->typeParams[i];
                m_typeParams.insert(f->typeParams[i]);
            }
            line(tpl + ">");
        }
        std::string ret;
        if (f->isCoroutine) ret = "_KsTask";
        else ret = f->returnType ? cppType(*f->returnType) : "void";
        write(std::string(m_indent * 4, ' '));
        for(auto& attr:f->attributes){
            if(attr=="naked")         line("__attribute__((naked))");
            else if(attr=="noreturn") line("[[noreturn]]");
            else if(attr=="noinline") line("__attribute__((noinline))");
            else if(attr=="inline")   write(std::string(m_indent*4,' ')+"inline ");
            else                      line("/* #["+attr+"] */");
        }
        // func main() -> int main()
        std::string fname = f->name;
        if (fname == "main") ret = "int";
        write(ret + " " + (prefix.empty() ? "" : prefix + "::") + fname + "(");
        bool firstParam = true;
        for (size_t i = 0; i < f->params.size(); i++) {
            if (f->params[i].name == "self") continue; // self = implicit this in C++
            if (!firstParam) write(", "); firstParam = false;
            std::string pct = cppType(f->params[i].type);
            write(pct + " " + f->params[i].name);
        }
        // Add override if implementing interface
        bool hasSelf = false;
        for (auto& p : f->params) if (p.name == "self") { hasSelf = true; break; }
        std::string overrideMark = !m_currentClassIfaces.empty() ? " override" : "";
        std::string constMark = hasSelf ? " const" : "";
        write(")" + constMark + overrideMark + " {\n");
        indent();
        if (hasSelf) line("auto& self = *this;");
        // Register pointer-typed params so member access inside the body uses ->
        std::unordered_set<std::string> addedParams;
        for (auto& p : f->params) {
            std::string ct = cppType(p.type);
            bool isPtr  = !ct.empty() && ct.back() == '*';
            bool isNode = m_userNodeTypes.count(p.type.base) > 0;
            static const std::unordered_set<std::string> builtinNodes = {
                "Node","Node2D","Sprite2D","Collider2D","AnimationPlayer"
            };
            if (isPtr || isNode || builtinNodes.count(p.type.base)) {
                m_ptrVars.insert(p.name);
                addedParams.insert(p.name);
            }
            m_varTypes[p.name] = p.type.base;
        }
        genBlock(f->body.get());
        for (auto& p : addedParams) m_ptrVars.erase(p);
        for (auto& tp : f->typeParams) m_typeParams.erase(tp);
        dedent();
        line("}");
        line("");
    }

    // -----------------------------------------------------------------------
    // Statements
    // -----------------------------------------------------------------------
    void genBlock(const BlockStmt* block) {
        if (!block) return;
        for (auto& s : block->stmts) genStmt(s.get());
    }

    void genStmt(const Stmt* s) {
        if (!s) return;
        switch (s->kind) {
            case Stmt::Kind::Let:      genLet(s);      break;
            case Stmt::Kind::Const:    genConst(s);    break;
            case Stmt::Kind::ExprStmt: genExprStmt(s); break;
            case Stmt::Kind::Return:   genReturn(s);   break;
            case Stmt::Kind::Break:    genBreak(s);    break;
            case Stmt::Kind::Continue: genContinue(s); break;
            case Stmt::Kind::If:       genIf(s);       break;
            case Stmt::Kind::While:    genWhile(s);    break;
            case Stmt::Kind::Loop:     genLoop(s);     break;
            case Stmt::Kind::ForC:     genForC(s);     break;
            case Stmt::Kind::ForIn:    genForIn(s);    break;
            case Stmt::Kind::Switch:   genSwitch(s);   break;
            case Stmt::Kind::Wait:     genWait(s);     break;
            case Stmt::Kind::AsmStmt:  genAsmStmt(s);  break;
            case Stmt::Kind::ExternDecl: break;
            case Stmt::Kind::FuncDecl:
                genFuncDecl(static_cast<const FuncDecl*>(s), "");
                break;
            case Stmt::Kind::Block: {
                line("{");
                indent();
                genBlock(static_cast<const BlockStmt*>(s));
                dedent();
                line("}");
                break;
            }
            default: break;
        }
    }

    // Returns true if expr is a scene.add() / scene.Add() / this.add() call,
    // which always returns a pointer — regardless of declared type.
    bool initIsNodeFactory(const Expr* e) const {
        if (!e || e->kind != Expr::Kind::Call) return false;
        auto* call = static_cast<const CallExpr*>(e);
        if (!call->callee || call->callee->kind != Expr::Kind::Member) return false;
        auto* m = static_cast<const MemberExpr*>(call->callee.get());
        return m->member == "add" || m->member == "Add";
    }

    void genLet(const Stmt* s) {
        auto* l = static_cast<const LetStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        std::string ct = cppType(l->type);

        // If the init is a node factory call (scene.add / this.add), the result
        // is always a pointer — force pointer type even if the declared type is
        // unknown (e.g. a node from another .ks file).
        bool fromFactory = initIsNodeFactory(l->init.get());
        if (fromFactory && !ct.empty() && ct.back() != '*')
            ct += "*";

        bool isPtr      = !ct.empty() && ct.back() == '*';
        bool isValType  = m_engineValueTypes.count(l->type.base) > 0;
        bool isStr      = l->type.base == "str";
        bool isUserNode = m_userNodeTypes.count(l->type.base) > 0;

        // Never emit const for: pointers, value types, strings, user nodes,
        // or anything coming from a factory call.
        bool needConst = !l->mut && !isPtr && !isValType && !isStr
                         && !isUserNode && !fromFactory;
        if (needConst)
            write("const ");

        // Track pointer vars so genMember uses -> instead of .
        if (isPtr || isUserNode || fromFactory)
            m_ptrVars.insert(l->name);

        // Track variable type so method calls know if it's a user class/struct
        m_varTypes[l->name] = l->type.base;

        write(ct + " " + l->name + " = ");
        genExpr(l->init.get());
        write(";\n");
    }

    void genExprStmt(const Stmt* s) {
        auto* e = static_cast<const ExprStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        genExpr(e->expr.get());
        write(";\n");
    }

    void genReturn(const Stmt* s) {
        auto* r = static_cast<const ReturnStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("return");
        if (r->value) { write(" "); genExpr(r->value.get()); }
        write(";\n");
    }

    void genBreak(const Stmt* s) {
        auto* b = static_cast<const BreakStmt*>(s);
        if (!b->label.empty()) line("goto __break_" + b->label + ";");
        else line("break;");
    }

    void genContinue(const Stmt* s) {
        auto* c = static_cast<const ContinueStmt*>(s);
        if (!c->label.empty()) line("goto __continue_" + c->label + ";");
        else line("continue;");
    }

    void genIf(const Stmt* s) {
        auto* i = static_cast<const IfStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("if ("); genExpr(i->cond.get()); write(") {\n");
        indent(); genBlock(i->then_.get()); dedent();
        if (i->else_) {
            line("} else {");
            indent(); genBlock(i->else_.get()); dedent();
        }
        line("}");
    }

    void genWhile(const Stmt* s) {
        auto* w = static_cast<const WhileStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("while ("); genExpr(w->cond.get()); write(") {\n");
        indent(); genBlock(w->body.get()); dedent();
        line("}");
        if (!w->label.empty()) {
            line("__break_" + w->label + ": ;");
            line("__continue_" + w->label + ": ;");
        }
    }

    void genLoop(const Stmt* s) {
        auto* l = static_cast<const LoopStmt*>(s);
        line("while (true) {");
        indent(); genBlock(l->body.get()); dedent();
        line("}");
        if (!l->label.empty()) {
            line("__break_" + l->label + ": ;");
            line("__continue_" + l->label + ": ;");
        }
    }

    void genForC(const Stmt* s) {
        auto* f = static_cast<const ForCStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("for (" + cppType(f->type) + " " + f->var + " = ");
        genExpr(f->init.get()); write("; ");
        genExpr(f->cond.get()); write("; ");
        genExpr(f->step.get()); write(") {\n");
        indent(); genBlock(f->body.get()); dedent();
        line("}");
        if (!f->label.empty()) {
            line("__break_" + f->label + ": ;");
            line("__continue_" + f->label + ": ;");
        }
    }

    void genForIn(const Stmt* s) {
        auto* f = static_cast<const ForInStmt*>(s);

        // Range expansion: for i in 0..10  ->  for (int i = 0; i < 10; i++)
        if (f->iterable->kind == Expr::Kind::Range) {
            auto* r = static_cast<const RangeExpr*>(f->iterable.get());
            write(std::string(m_indent * 4, ' '));
            write("for (" + cppType(f->type) + " " + f->var + " = ");
            genExpr(r->from.get()); write("; ");
            write(f->var + (r->inclusive ? " <= " : " < "));
            genExpr(r->to.get()); write("; ");
            write(f->var + "++) {\n");
            indent(); genBlock(f->body.get()); dedent();
            line("}");
            if (!f->label.empty()) {
                line("__break_" + f->label + ": ;");
                line("__continue_" + f->label + ": ;");
            }
            return;
        }

        write(std::string(m_indent * 4, ' '));
        write("for (const " + cppType(f->type) + "& " + f->var + " : ");
        genExpr(f->iterable.get()); write(") {\n");
        indent(); genBlock(f->body.get()); dedent();
        line("}");
        if (!f->label.empty()) {
            line("__break_" + f->label + ": ;");
            line("__continue_" + f->label + ": ;");
        }
    }

    void genSwitch(const Stmt* s) {
        auto* sw = static_cast<const SwitchStmt*>(s);
        write(std::string(m_indent * 4, ' '));
        write("switch ("); genExpr(sw->expr.get()); write(") {\n");
        for (auto& c : sw->cases) {
            if (c.isDefault) {
                line("default:");
            } else {
                for (auto& v : c.values) {
                    write(std::string(m_indent * 4, ' '));
                    write("case ");
                    // BUG-11 fix: qualify enum variants with their enum name.
                    // e.g. case Idle: -> case State::Idle:
                    if (v->kind == Expr::Kind::Ident) {
                        auto* id = static_cast<const IdentExpr*>(v.get());
                        auto it = m_enumVariants.find(id->name);
                        if (it != m_enumVariants.end())
                            write(it->second + "::" + id->name);
                        else
                            genExpr(v.get());
                    } else {
                        genExpr(v.get());
                    }
                    write(":\n");
                }
            }
            indent();
            for (auto& st : c.body) genStmt(st.get());
            dedent();
        }
        line("}");
    }

    void genWait(const Stmt* s) {
        auto* w = static_cast<const WaitStmt*>(s);
        std::string pad = std::string(m_indent * 4, ' ');
        line("#if __cplusplus >= 202002L");
        write(pad + "co_yield (float)(");
        genExpr(w->duration.get());
        write(");\n");
        line("#else");
        line(pad + "/* wait: requires -std=c++20 */");
        line("#endif");
    }


    // -----------------------------------------------------------------------
    // Expressions
    // -----------------------------------------------------------------------
    void genExpr(const Expr* e) {
        if (!e) return;
        switch (e->kind) {
            case Expr::Kind::IntLit:
                write(std::to_string(static_cast<const IntLitExpr*>(e)->value));
                break;
            case Expr::Kind::FloatLit: {
                // Emit as float literal (f suffix) to match engine's float types
                auto fval = static_cast<const FloatLitExpr*>(e)->value;
                std::ostringstream oss;
                oss << std::setprecision(8) << fval;
                std::string fs = oss.str();
                // Ensure it has a decimal point
                if (fs.find('.') == std::string::npos && fs.find('e') == std::string::npos)
                    fs += ".0";
                write(fs + "f");
                break;
            }
            case Expr::Kind::BoolLit:
                write(static_cast<const BoolLitExpr*>(e)->value ? "true" : "false");
                break;
            case Expr::Kind::StrLit: {
                auto* sl = static_cast<const StrLitExpr*>(e);
                // Re-escape the string for C++
                std::string out = "\"";
                for (char c : sl->value) {
                    if      (c == '\n') out += "\\n";
                    else if (c == '\t') out += "\\t";
                    else if (c == '\r') out += "\\r";
                    else if (c == '"')  out += "\\\"";
                    else if (c == '\\') out += "\\\\";
                    else                out += c;
                }
                write(out + "\"");
                break;
            }
            case Expr::Kind::NullLit:
            case Expr::Kind::NoneLit:
                write("std::nullopt");
                break;
            case Expr::Kind::Ident:
                genIdent(static_cast<const IdentExpr*>(e));
                break;
            case Expr::Kind::Unary:
                genUnary(static_cast<const UnaryExpr*>(e));
                break;
            case Expr::Kind::Binary:
                genBinary(static_cast<const BinaryExpr*>(e));
                break;
            case Expr::Kind::Assign:
                genAssign(static_cast<const AssignExpr*>(e));
                break;
            case Expr::Kind::Call:
                genCall(static_cast<const CallExpr*>(e));
                break;
            case Expr::Kind::Member:
            case Expr::Kind::SafeMember:
                genMember(static_cast<const MemberExpr*>(e));
                break;
            case Expr::Kind::Index:
                genIndex(static_cast<const IndexExpr*>(e));
                break;
            case Expr::Kind::Cast:
                genCast(static_cast<const CastExpr*>(e));
                break;
            case Expr::Kind::NullCoal:
                genNullCoal(static_cast<const NullCoalExpr*>(e));
                break;
            case Expr::Kind::ForceUnwrap:
                genExpr(static_cast<const ForceUnwrapExpr*>(e)->value.get());
                write(".value()");
                break;
            case Expr::Kind::Some_:
                genExpr(static_cast<const SomeExpr*>(e)->value.get());
                break;
            case Expr::Kind::ArrayLit:
                genArrayLit(static_cast<const ArrayLitExpr*>(e));
                break;
            case Expr::Kind::TupleLit:
                genTupleLit(static_cast<const TupleLitExpr*>(e));
                break;
            case Expr::Kind::StructInit:
                genStructInit(static_cast<const StructInitExpr*>(e));
                break;
            case Expr::Kind::Range:
                write("/* range */");
                break;
            case Expr::Kind::Spawn:
                write("_ks_spawn(");
                genExpr(static_cast<const SpawnExpr*>(e)->call.get());
                write(")");
                break;
            case Expr::Kind::Deref:
                write("(*"); genExpr(static_cast<const DerefExpr*>(e)->ptr.get()); write(")");
                break;
            case Expr::Kind::AddrOf: {
                auto* ao=static_cast<const AddrOfExpr*>(e);
                write(ao->mut_ ? "&" : "(const void*)&");
                genExpr(ao->value.get());
                break;
            }
            case Expr::Kind::FuncExpr:
                genFuncExpr(static_cast<const FuncExpr*>(e));
                break;
            case Expr::Kind::Propagate:
                genPropagate(static_cast<const PropagateExpr*>(e));
                break;
            default: {
                // F-string literal: FStrLitExpr falls here if Kind::FStr isn't
                // matched above — handle via dynamic_cast so we're resilient to
                // whatever the enum value is named.
                if (auto* fs = dynamic_cast<const FStrLitExpr*>(e)) {
                    // f"Hello {name}!" ->
                    // ([&]{ std::ostringstream _ks_ss; _ks_ss << "Hello " << name; return _ks_ss.str(); }())
                    write("([&]{ std::ostringstream _ks_ss; ");
                    size_t exprIdx = 0;
                    for (size_t i = 0; i < fs->strParts.size(); i++) {
                        if (!fs->strParts[i].empty()) {
                            std::string lit = "\"";
                            for (char c : fs->strParts[i]) {
                                if      (c == '\n') lit += "\\n";
                                else if (c == '\t') lit += "\\t";
                                else if (c == '"')  lit += "\\\"";
                                else if (c == '\\') lit += "\\\\";
                                else                lit += c;
                            }
                            lit += "\"";
                            write("_ks_ss << " + lit + "; ");
                        }
                        if (exprIdx < fs->exprParts.size()) {
                            write("_ks_ss << ");
                            genExpr(fs->exprParts[exprIdx++].get());
                            write("; ");
                        }
                    }
                    write("return _ks_ss.str(); }())");
                } else {
                    write("/* unknown expr */");
                }
                break;
            }
        }
    }

    void genIdent(const IdentExpr* e) {
        static const std::unordered_map<std::string, std::string> builtins = {
            // Print is handled in genCall, not here
            {"MouseDown",          "IsMouseButtonDown"},
            {"MousePressed",       "IsMouseButtonPressed"},
            {"MouseReleased",      "IsMouseButtonReleased"},
            {"GetMouseX",          "GetMouseX"},
            {"GetMouseY",          "GetMouseY"},
            {"GetWorldMouseX",     "GetWorldMouseX"},
            {"GetWorldMouseY",     "GetWorldMouseY"},
            {"GetMouseDeltaX",     "GetMouseDeltaX"},
            {"GetMouseDeltaY",     "GetMouseDeltaY"},
            {"GetMouseScroll",     "GetMouseScroll"},
            {"GetDeltaTime",       "GetDeltaTime"},
            {"GetFPS",             "GetFPS"},
            {"GetTime",            "GetTime"},
            {"SetTimeScale",       "SetTimeScale"},
            {"DebugMode",          "DebugMode"},
            {"IsDebugMode",        "IsDebugMode"},
            {"Emit",               "Emit"},
            {"Connect",            "Connect"},
            {"GetNode",            "GetNode"},
            {"GetWindowWidth",     "GetWindowWidth"},
            {"GetWindowHeight",    "GetWindowHeight"},
            {"LoadSound",          "LoadSound"},
            {"LoadMusic",          "LoadMusic"},
            {"PlaySound",          "PlaySound"},
            {"StopSound",          "StopSound"},
            {"PauseSound",         "PauseSound"},
            {"ResumeSound",        "ResumeSound"},
            {"PlayMusic",          "PlayMusic"},
            {"StopMusic",          "StopMusic"},
            {"PauseMusic",         "PauseMusic"},
            {"ResumeMusic",        "ResumeMusic"},
            {"SetMusicVolume",     "SetMusicVolume"},
            {"SetSoundVolume",     "SetSoundVolume"},
            {"SetMasterVolume",    "SetMasterVolume"},
            {"UpdateMusic",        "UpdateMusic"},
            {"LoadTexture",        "LoadTexture"},
            {"UnloadTexture",      "UnloadTexture"},
            {"Distance",           "glm::distance"},
            {"Sqrt",               "sqrtf"},
            {"Abs",                "fabsf"},
            {"Floor",              "floorf"},
            {"Ceil",               "ceilf"},
            {"Round",              "roundf"},
            {"Sin",                "sinf"},
            {"Cos",                "cosf"},
            {"Tan",                "tanf"},
            {"Atan2",              "atan2f"},
            {"Clamp",              "glm::clamp"},
            {"Lerp",               "glm::mix"},
            {"Min",                "std::min"},
            {"Max",                "std::max"},
        };
        auto it = builtins.find(e->name);
        if (it != builtins.end()) {
            write(it->second);
        } else {
            // Qualify enum variants: South -> Direction::South
            auto ev = m_enumVariants.find(e->name);
            if (ev != m_enumVariants.end())
                write(ev->second + "::" + e->name);
            else
                write(e->name);
        }
    }

    void genUnary(const UnaryExpr* e) {
        if (e->postfix) {
            genExpr(e->operand.get());
            write(e->op);
        } else {
            write(e->op);
            genExpr(e->operand.get());
        }
    }

    void genBinary(const BinaryExpr* e) {
        write("(");
        genExpr(e->left.get());
        write(" " + e->op + " ");
        genExpr(e->right.get());
        write(")");
    }

    void genAssign(const AssignExpr* e) {
        genExpr(e->target.get());
        write(" " + e->op + " ");
        genExpr(e->value.get());
    }

    void genCall(const CallExpr* e) {
        if (e->callee->kind == Expr::Kind::Ident) {
            auto* id = static_cast<const IdentExpr*>(e->callee.get());

            // Print -> _ks_print (variadic helper that handles std::string .c_str())
            // We emit printf directly but wrap any member access that might be
            // std::string (like node->name) with a c_str() call via a helper macro.
            // The generated header includes: #define _KS_STR(x) (x).c_str()
            // For simplicity, we use printf but caller must use %s with .c_str().
            // We handle this by generating a KsPrint variadic that casts strings.
            if (id->name == "Print") {
                // Emit as std::cout << arg1 << " " << arg2 << ... << std::endl
                // std::endl flushes immediately so output appears in real time.
                if (e->args.empty()) {
                    write("std::cout << std::endl");
                } else {
                    write("std::cout");
                    for (size_t i = 0; i < e->args.size(); i++) {
                        if (i > 0) write(" << \" \"");
                        write(" << ");
                        genExpr(e->args[i].get());
                    }
                    write(" << std::endl");
                }
                return;
            }

            // ToString(x) -> std::to_string(x).c_str()
            if (id->name == "ToString" && e->args.size() == 1) {
                write("std::to_string(");
                genExpr(e->args[0].get());
                write(").c_str()");
                return;
            }

            // DrawText with format args:
            // DrawText("FPS: %d", 10, 20, 16, GREEN, fps) -- format + args
            // DrawText("text", x, y, size, color)          -- plain, pass through
            // We detect: if first arg is a string with % and there are args after color
            // Signature: DrawText(fmt, x, y, size, color [, fmtargs...])
            if (id->name == "DrawText" && e->args.size() >= 5) {
                // args: [0]=text, [1]=x, [2]=y, [3]=size, [4]=color, [5+]=format args
                size_t fmtArgCount = e->args.size() - 5;
                if (fmtArgCount > 0) {
                    // Has format args -- wrap in snprintf
                    write("{ char _ks_buf[512]; snprintf(_ks_buf, sizeof(_ks_buf), ");
                    genExpr(e->args[0].get()); // format string
                    for (size_t i = 5; i < e->args.size(); i++) {
                        write(", ");
                        genExpr(e->args[i].get());
                    }
                    write("); DrawText(_ks_buf, (float)");
                    genExpr(e->args[1].get()); write(", (float)");
                    genExpr(e->args[2].get()); write(", (int)");
                    genExpr(e->args[3].get()); write(", ");
                    genExpr(e->args[4].get());
                    write("); }");
                    return;
                } else {
                    // Plain DrawText(text, x, y, size, color)
                    write("DrawText((const char*)");
                    genExpr(e->args[0].get()); write(", (float)");
                    genExpr(e->args[1].get()); write(", (float)");
                    genExpr(e->args[2].get()); write(", (int)");
                    genExpr(e->args[3].get()); write(", ");
                    genExpr(e->args[4].get());
                    write(")");
                    return;
                }
            }

            // Vec2(x, y) -> Vector2{x, y}
            if (id->name == "Vec2") {
                write("Vector2{");
                for (size_t i = 0; i < e->args.size(); i++) {
                    if (i > 0) write(", ");
                    genExpr(e->args[i].get());
                }
                write("}");
                return;
            }

            // HashMap() → {} (default construct the unordered_map)
            if (id->name == "HashMap") {
                write("{}");
                return;
            }

            // Camera2D(x, y, zoom, rot) -> Camera2D{x, y, zoom, rot}
            if (id->name == "Camera2D") {
                write("Camera2D(");
                for (size_t i = 0; i < e->args.size(); i++) {
                    if (i > 0) write(", ");
                    genExpr(e->args[i].get());
                }
                write(")");
                return;
            }

            // KeyDown/Pressed/Released -> IsKeyDown etc. with Key::Code cast
            static const std::unordered_map<std::string,std::string> keyFuncs = {
                {"KeyDown",     "IsKeyDown"},
                {"KeyPressed",  "IsKeyPressed"},
                {"KeyReleased", "IsKeyReleased"},
            };
            auto kf = keyFuncs.find(id->name);
            if (kf != keyFuncs.end() && e->args.size() == 1) {
                write(kf->second + "((Key::Code)(");
                genExpr(e->args[0].get());
                write("))");
                return;
            }

            // scene.add(TypeName, "name") -> scene.Add<TypeName>("name")
            // node.add(TypeName, "name")  -> node->AddChild<TypeName>("name")
            if (e->callee->kind == Expr::Kind::Ident) {
                // handled below via member call path
            }
        }

        // Member call: obj.method(args) or obj.add(Type, "name")
        if (e->callee->kind == Expr::Kind::Member) {
            auto* m = static_cast<const MemberExpr*>(e->callee.get());

            // If the receiver is a user-defined class/struct, skip all built-in
            // collection transforms and fall through to plain method call.
            bool skipTransforms = objectIsUserType(m->object.get());

            // obj.add(Type, "name"):
            //   if obj is a node pointer -> obj->AddChild<Type>("name")
            //   if obj is a scene/value  -> obj.Add<Type>("name")
            if (m->member == "add" && e->args.size() == 2) {
                bool objIsNode = false;
                if (m->object->kind == Expr::Kind::Ident) {
                    auto* objId = static_cast<const IdentExpr*>(m->object.get());
                    static const std::unordered_set<std::string> builtinNodes = {
                        "Node","Node2D","Sprite2D","Collider2D","AnimationPlayer"
                    };
                    objIsNode = objId->name == "this" ||
                                builtinNodes.count(objId->name) ||
                                m_userNodeTypes.count(objId->name) ||
                                m_ptrVars.count(objId->name);
                }
                genExpr(m->object.get());
                if (objIsNode) {
                    write("->AddChild<");
                } else {
                    write(".Add<");
                }
                genExpr(e->args[0].get());
                write(">(");
                genExpr(e->args[1].get());
                write(")");
                return;
            }

            // scene.update(dt)  -> scene.Update(dt)
            // scene.draw()      -> scene.Draw()
            // scene.scan()      -> scene.Scan()
            // scene.remove(n)   -> scene.Remove(n)
            // scene.get(n)      -> scene.GetNode(n)
            // Only safe lowercase aliases that don't clash with user methods or
            // HashMap/Array methods. "get" and "remove" were removed — they
            // conflict with HashMap.get(key) and Array/HashMap.remove(key).
            // Use scene.GetNode("name") and scene.Remove(node) directly.
            static const std::unordered_map<std::string,std::string> sceneMethods = {
                {"update", "Update"},
                {"draw",   "Draw"},
                {"scan",   "Scan"},
            };
            auto sm = sceneMethods.find(m->member);
            if (sm != sceneMethods.end()) {
                genExpr(m->object.get());
                write("." + sm->second + "(");
                for (size_t i = 0; i < e->args.size(); i++) {
                    if (i > 0) write(", ");
                    genExpr(e->args[i].get());
                }
                write(")");
                return;
            }

            // ── File.method(args) ───────────────────────────────────────
            // File.read(path) → _ks_file_read(path)  etc.
            if (m->object->kind == Expr::Kind::Ident) {
                auto* objId = static_cast<const IdentExpr*>(m->object.get());
                if (objId->name == "File") {
                    static const std::unordered_map<std::string,std::string> fileMethods = {
                        {"read",   "_ks_file_read"},
                        {"write",  "_ks_file_write"},
                        {"append", "_ks_file_append"},
                        {"exists", "_ks_file_exists"},
                        {"delete", "_ks_file_delete"},
                        {"lines",  "_ks_file_lines"},
                    };
                    auto it = fileMethods.find(m->member);
                    if (it != fileMethods.end()) {
                        write(it->second + "(");
                        for (size_t i = 0; i < e->args.size(); i++) {
                            if (i > 0) write(", ");
                            genExpr(e->args[i].get());
                        }
                        write(")");
                        return;
                    }
                }
            }

            // ── Skip ALL built-in transforms for user class/struct receivers ──
            if (skipTransforms) goto plain_method_call;

            // ── Universal collection methods (work on strings, arrays, maps) ──
            // Emitted as direct C++ so they work on any container type.
            if (m->member == "len" && e->args.empty()) {
                write("(int)"); genExpr(m->object.get()); write(".size()");
                return;
            }
            if (m->member == "isEmpty" && e->args.empty()) {
                genExpr(m->object.get()); write(".empty()");
                return;
            }
            if (m->member == "clear" && e->args.empty()) {
                genExpr(m->object.get()); write(".clear()");
                return;
            }

            // ── Array method calls: arr.push(v), arr.pop(), etc. ────────
            if (m->member == "push" && e->args.size() == 1) {
                genExpr(m->object.get()); write(".push_back(");
                genExpr(e->args[0].get()); write(")");
                return;
            }
            if (m->member == "pop" && e->args.empty()) {
                write("([&](){ auto _v = ");
                genExpr(m->object.get()); write(".back(); ");
                genExpr(m->object.get()); write(".pop_back(); return _v; }())");
                return;
            }
            if (m->member == "first" && e->args.empty()) {
                write("("); genExpr(m->object.get());
                write(".empty() ? std::nullopt : std::make_optional(");
                genExpr(m->object.get()); write(".front()))");
                return;
            }
            if (m->member == "last" && e->args.empty()) {
                write("("); genExpr(m->object.get());
                write(".empty() ? std::nullopt : std::make_optional(");
                genExpr(m->object.get()); write(".back()))");
                return;
            }
            // arr.has(v) — for vector: std::find; for map: .count()
            // Since we can't distinguish at codegen time, we emit .count() which
            // exists on unordered_map, and a find-based helper for vectors.
            // KonScript convention: use .has() on both, codegen picks the right one
            // by checking if the object name is a known map var (not possible here),
            // so we emit a generic approach that compiles for both via template deduction.
            if (m->member == "has" && e->args.size() == 1) {
                write("(_ks_has("); genExpr(m->object.get());
                write(", "); genExpr(e->args[0].get()); write("))");
                return;
            }

            // ── HashMap method calls ─────────────────────────────────────
            if (m->member == "set" && e->args.size() == 2) {
                genExpr(m->object.get()); write("[");
                genExpr(e->args[0].get()); write("] = ");
                genExpr(e->args[1].get());
                return;
            }
            if (m->member == "get" && e->args.size() == 1) {
                write("([&]() -> std::optional<decltype(");
                genExpr(m->object.get()); write(".begin()->second)> {");
                write(" auto _it = "); genExpr(m->object.get());
                write(".find("); genExpr(e->args[0].get()); write(");");
                write(" return _it == "); genExpr(m->object.get());
                write(".end() ? std::nullopt : std::make_optional(_it->second); }())");
                return;
            }
            if (m->member == "remove" && e->args.size() == 1) {
                genExpr(m->object.get()); write(".erase(");
                genExpr(e->args[0].get()); write(")");
                return;
            }
            // map.has(k) — use .count() which is correct for unordered_map
            if (m->member == "mapHas" && e->args.size() == 1) {
                write("("); genExpr(m->object.get()); write(".count(");
                genExpr(e->args[0].get()); write(") > 0)");
                return;
            }
            // For HashMap.has() we also accept plain .has() and emit .count()
            // This is safe because std::vector doesn't have .count()
            // so at runtime the right container's method will be called.
            // We wrap in parens to fix operator precedence with <<.

            // ── Str method calls: str.split(delim) etc. ─────────────────
            // Only string-specific methods here — len/isEmpty/clear handled above
            {
                static const std::unordered_map<std::string,std::string> strMethods = {
                    {"split",    "_ks_str_split"},
                    {"trim",     "_ks_str_trim"},
                    {"contains", "_ks_str_contains"},
                    {"replace",  "_ks_str_replace"},
                    {"starts",   "_ks_str_starts"},
                    {"ends",     "_ks_str_ends"},
                    {"upper",    "_ks_str_upper"},
                    {"lower",    "_ks_str_lower"},
                    {"substr",   "_ks_str_substr"},
                    {"toInt",    "_ks_str_toInt"},
                    {"toFloat",  "_ks_str_toFloat"},
                };
                auto it = strMethods.find(m->member);
                if (it != strMethods.end()) {
                    write(it->second + "(");
                    genExpr(m->object.get());
                    for (auto& arg : e->args) { write(", "); genExpr(arg.get()); }
                    write(")");
                    return;
                }
            }

            // AssetManager.init(...)  -> AssetManager::init(...)
            // AssetManager.isPackMode() etc — static methods via ::
            if (m->object->kind == Expr::Kind::Ident) {
                auto* objId = static_cast<const IdentExpr*>(m->object.get());
                if (objId->name == "AssetManager") {
                    write("AssetManager::" + m->member + "(");
                    for (size_t i = 0; i < e->args.size(); i++) {
                        if (i > 0) write(", ");
                        genExpr(e->args[i].get());
                    }
                    write(")");
                    return;
                }
            }

            // DrawText with 5 args (text, x, y, size, Color) -- pass through directly
            // All other method calls (also landing point for skipTransforms goto)
            plain_method_call:
            genExpr(m->object.get());

            // Use -> for node pointer objects
            bool useArrow = false;
            if (m->object->kind == Expr::Kind::Ident) {
                auto* objId = static_cast<const IdentExpr*>(m->object.get());
                static const std::unordered_set<std::string> builtinNodes = {
                    "Node","Node2D","Sprite2D","Collider2D","AnimationPlayer"
                };
                if (objId->name != "self" &&
                   (objId->name == "this" ||
                    builtinNodes.count(objId->name) ||
                    m_userNodeTypes.count(objId->name) ||
                    m_ptrVars.count(objId->name)))
                    useArrow = true;
            }
            write(useArrow ? "->" : ".");
            write(m->member + "(");
            for (size_t i = 0; i < e->args.size(); i++) {
                if (i > 0) write(", ");
                genExpr(e->args[i].get());
            }
            write(")");
            return;
        }

        // Plain function call
        genExpr(e->callee.get());
        write("(");
        for (size_t i = 0; i < e->args.size(); i++) {
            if (i > 0) write(", ");
            genExpr(e->args[i].get());
        }
        write(")");
    }

    // Returns true if the object in a member call is a user-defined class/struct.
    // Used to skip built-in array/string method transforms for user types.
    bool objectIsUserType(const Expr* obj) const {
        if (!obj || obj->kind != Expr::Kind::Ident) return false;
        auto* id = static_cast<const IdentExpr*>(obj);
        auto it = m_varTypes.find(id->name);
        if (it == m_varTypes.end()) return false;
        const std::string& t = it->second;
        return m_classNames.count(t) || m_structNames.count(t);
    }

    void genInterface(const Stmt* s) {
        auto* id = static_cast<const InterfaceDecl*>(s);
        m_interfaceNames.insert(id->name);
        // Template prefix for generic interfaces
        if (!id->typeParams.empty()) {
            std::string tpl = "template<";
            for (size_t i=0;i<id->typeParams.size();i++) {
                if(i) tpl+=", "; tpl+="typename "+id->typeParams[i];
            }
            line(tpl + ">");
        }
        line("struct " + id->name + " {");
        indent();
        for (auto& m : id->methods) {
            std::string ret = m.returnType ? cppType(*m.returnType) : "void";
            std::string sig = "virtual " + ret + " " + m.name + "(";
            bool first = true;
            bool hasSelf = false;
            for (auto& p : m.params) {
                if (p.name == "self") { hasSelf = true; continue; }
                if (!first) sig += ", "; first = false;
                sig += cppType(p.type) + " " + p.name;
            }
            std::string constQ = hasSelf ? " const" : "";
            if (m.defaultBody) {
                sig += ")" + constQ;
                line(sig + " {");
                indent();
                genBlock(m.defaultBody.get());
                dedent();
                line("}");
            } else {
                line(sig + ")" + constQ + " = 0;");
            }
        }
        line("virtual ~" + id->name + "() = default;");
        dedent();
        line("};");
        line("");
    }

    void genExtern(const Stmt* s) {
        auto* e=static_cast<const ExternDecl*>(s);
        std::string lnk=e->linkage.empty()?"C":e->linkage;
        std::string ret=e->returnType.base.empty()?"void":cppType(e->returnType);
        std::string sig="extern \""+lnk+"\" "+ret+" "+e->name+"(";
        for(size_t i=0;i<e->params.size();i++){
            if(i)sig+=", ";
            sig+=cppType(e->params[i].type);
            if(!e->params[i].name.empty())sig+=" "+e->params[i].name;
        }
        if(e->variadic){if(!e->params.empty())sig+=", ";sig+="...";}
        sig+=");";
        line(sig);
    }

    void genAsmStmt(const Stmt* s) {
        auto* a=static_cast<const AsmStmt*>(s);
        std::string pad=std::string(m_indent*4,' ');
        std::string tmpl = a->tmpl;
        if (m_intelAsm)
            tmpl = ".intel_syntax noprefix\\n\\t" + tmpl + "\\n\\t.att_syntax prefix";
        write(pad+"asm volatile(\""+tmpl+"\"");
        if(!a->outputs.empty()||!a->inputs.empty()||!a->clobbers.empty()){
            write("\n"+pad+"    : ");
            for(size_t i=0;i<a->outputs.size();i++){
                if(i)write(", ");
                write("\""+a->outputs[i]+"\" (");
                genExpr(a->outExprs[i].get()); write(")");
            }
        }
        if(!a->inputs.empty()||!a->clobbers.empty()){
            write("\n"+pad+"    : ");
            for(size_t i=0;i<a->inputs.size();i++){
                if(i)write(", ");
                write("\""+a->inputs[i]+"\" (");
                genExpr(a->inExprs[i].get()); write(")");
            }
        }
        if(!a->clobbers.empty()){
            write("\n"+pad+"    : ");
            for(size_t i=0;i<a->clobbers.size();i++){
                if(i)write(", ");
                write("\""+a->clobbers[i]+"\"");
            }
        }
        write(");\n");
    }

    void genFuncExpr(const FuncExpr* e) {
        write("[&](");
        for (size_t i = 0; i < e->params.size(); i++) {
            if (i > 0) write(", ");
            std::string pct = cppType(e->params[i].type);
            write(pct + " " + e->params[i].name);
            m_varTypes[e->params[i].name] = e->params[i].type.base;
        }
        write(") ");
        if (e->returnType) write("-> " + cppType(*e->returnType) + " ");
        write("{\n");
        indent(); genBlock(e->body.get()); dedent();
        write(std::string(m_indent * 4, ' ') + "}");
    }

    void genPropagate(const PropagateExpr* e) {
        write("([&]{ auto _ks_p = ");
        genExpr(e->value.get());
        // if not ok: early-return Err; else: unwrap value
        std::string tail = "; if (!_ks_p.ok) return decltype(_ks_p)::Err(_ks_p.error);";
        tail += " return _ks_p.value; }())";
        write(tail);
    }

    void genMember(const MemberExpr* e) {
        // Namespace access: Key.A -> Key::A, Mouse.Left -> Mouse::Left
        // Also handles user enums: Direction.North -> Direction::North
        if (e->object->kind == Expr::Kind::Ident) {
            auto* id = static_cast<const IdentExpr*>(e->object.get());
            static const std::unordered_set<std::string> cppNamespaces = {
                "Key", "Mouse", "Gamepad", "AssetManager"
            };
            // User-defined enums also use :: for variant access
            if (cppNamespaces.count(id->name) || m_enumNames.count(id->name)) {
                if (!cppNamespaces.count(id->name)) {
                    // User enum: Direction.North -> Direction::North  (no alias remapping)
                    write(id->name + "::" + e->member);
                    return;
                }
            if (cppNamespaces.count(id->name)) {
                // AssetManager uses :: (static methods)
                if (id->name == "AssetManager") {
                    write("AssetManager::" + e->member);
                    return;
                }
                static const std::unordered_map<std::string,std::string> keyAliases = {
                    {"Esc", "Escape"}, {"ESC", "Escape"},
                    {"Return", "Enter"}, {"Del", "Delete"},
                    {"LShift", "Shift"}, {"RShift", "Shift"},
                    {"LCtrl",  "Ctrl"},  {"RCtrl",  "Ctrl"},
                };
                std::string member = e->member;
                if (id->name == "Key") {
                    auto it = keyAliases.find(member);
                    if (it != keyAliases.end()) member = it->second;
                }
                write(id->name + "::" + member);
                return;
            }
            } // close cppNamespaces.count check
        }

        // Use -> for node pointer types and tracked pointer variables
        bool useArrow = false;
        if (e->object->kind == Expr::Kind::Ident) {
            auto* id = static_cast<const IdentExpr*>(e->object.get());
            static const std::unordered_set<std::string> builtinNodes = {
                "Node","Node2D","Sprite2D","Collider2D","AnimationPlayer"
            };
            if (id->name != "self" &&
               (id->name == "this" ||
                builtinNodes.count(id->name) ||
                m_userNodeTypes.count(id->name) ||
                m_ptrVars.count(id->name)))
                useArrow = true;
        }
        if (e->safe) {
            // ?.  safe access
            // Pointer types: !ptr → nullopt; ptr->member
            // Optional types: !opt → nullopt; opt->member (optional has operator->)
            write("([&](){ auto& _o = ");
            genExpr(e->object.get());
            write(";\n");
            if (useArrow)
                write(std::string((m_indent+1)*4, ' ') + "if (!_o) return decltype(std::make_optional(_o->" + e->member + ")){}; ");
            else
                write(std::string((m_indent+1)*4, ' ') + "if (!_o) return decltype(std::make_optional((*_o)." + e->member + ")){}; ");
            write("return std::make_optional(");
            write(useArrow ? "_o->" : "(*_o).");
            write(e->member + "); }())");
            return;
        }
        genExpr(e->object.get());
        write(useArrow ? "->" : ".");
        write(e->member);
    }

    void genIndex(const IndexExpr* e) {
        genExpr(e->object.get());
        write("[");
        genExpr(e->index.get());
        write("]");
    }

    void genCast(const CastExpr* e) {
        if (e->target.isPtr)
            write("reinterpret_cast<" + cppType(e->target) + ">(");
        else
            write("static_cast<" + cppType(e->target) + ">(");
        genExpr(e->value.get());
        write(")");
    }

    void genNullCoal(const NullCoalExpr* e) {
        genExpr(e->left.get());
        write(".value_or(");
        genExpr(e->right.get());
        write(")");
    }

    void genArrayLit(const ArrayLitExpr* e) {
        write("{");
        for (size_t i = 0; i < e->elements.size(); i++) {
            if (i > 0) write(", ");
            genExpr(e->elements[i].get());
        }
        write("}");
    }

    void genTupleLit(const TupleLitExpr* e) {
        write("std::make_tuple(");
        for (size_t i = 0; i < e->elements.size(); i++) {
            if (i > 0) write(", ");
            genExpr(e->elements[i].get());
        }
        write(")");
    }

    void genStructInit(const StructInitExpr* e) {
        // For classes implementing interfaces, they are non-aggregate
        // (have virtual base). Use lambda-based field assignment.
        if (m_classNames.count(e->typeName)) {
            write("([&]{ " + e->typeName + " _ks_obj{}; ");
            for (auto& f : e->fields) {
                write("_ks_obj." + f.name + " = ");
                genExpr(f.value.get());
                write("; ");
            }
            write("return _ks_obj; }())");
        } else {
            write(e->typeName + "{");
            for (size_t i = 0; i < e->fields.size(); i++) {
                if (i > 0) write(", ");
                write("." + e->fields[i].name + " = ");
                genExpr(e->fields[i].value.get());
            }
            write("}");
        }
    }
};

} // namespace KonScript
