#pragma once
// ---------------------------------------------------------------------------
// KonScript LLVM IR Generator
//
// Walks the same AST as Codegen but emits LLVM IR text (.ll) instead of C++.
// The .ll file is then compiled and linked by the editor via subprocesses:
//
//   llc  -filetype=obj  out.ll  -o out.o  --mtriple=<triple>
//   lld  -o mygame  out.o  KonEngine-<platform>.a  <platform-libs>
//
// Uses the alloca/load/store pattern so mem2reg can promote locals to SSA
// registers — the same strategy clang uses for local variables. No manual
// phi-node insertion needed.
//
// Design mirrors Codegen: one header, generate() takes a Program& and returns
// a std::string containing the full .ll file.
// ---------------------------------------------------------------------------
#include "ast.hpp"
#include <string>
#include <sstream>
#include <vector>
#include <unordered_map>
#include <unordered_set>

namespace KonScript {

class IRGen {
public:
    // -----------------------------------------------------------------------
    // Target triple — controls codegen target for llc/lld
    // -----------------------------------------------------------------------
    struct Target {
        std::string triple;        // e.g. "x86_64-pc-linux-gnu"
        std::string dataLayout;    // LLVM datalayout string
        std::string platformLibs;  // extra linker flags (-lGL -ldl etc.)

        static Target linux64() {
            return {
                "x86_64-pc-linux-gnu",
                "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
                "-lGL -ldl -lpthread -lX11 -lXrandr -lXi -lm"
            };
        }
        static Target windows64() {
            return {
                "x86_64-pc-windows-msvc19.0.0",
                "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
                "opengl32.lib gdi32.lib winmm.lib user32.lib kernel32.lib"
            };
        }
        static Target wasm32() {
            return {
                "wasm32-unknown-emscripten",
                "e-m:e-p:32:32-i64:64-n32:64-S128",
                ""
            };
        }
    };

    struct Error {
        std::string message;
        int line = 0, col = 0;
    };

    const std::vector<Error>& errors() const { return m_errors; }
    bool hasErrors() const { return !m_errors.empty(); }

    void setTarget(Target t) { m_target = std::move(t); }

    // -----------------------------------------------------------------------
    // Entry point — returns the full .ll file as a string
    // -----------------------------------------------------------------------
    std::string generate(const Program& prog) {
        m_out.str("");
        m_globalStr.str("");
        m_header.str("");
        m_errors.clear();
        m_strings.clear();
        m_strCount   = 0;
        m_tmpCount   = 0;
        m_labelCount = 0;
        m_locals.clear();
        m_funcRetType = "void";

        // Module header — written to m_header so it always comes first
        hdr("; Generated by KonScript IRGen — do not edit");
        hdr("; Source: " + prog.filename);
        hdr("target datalayout = \"" + m_target.dataLayout + "\"");
        hdr("target triple = \"" + m_target.triple + "\"");
        hdr("");

        // Runtime declarations
        emitRuntimeDecls();

        // Generate all top-level definitions (may populate m_globalStr)
        // Note: no forward-declare pass needed — LLVM resolves forward refs
        // within the same module. declare is only for truly external symbols
        // (printf, malloc, etc.) which are handled in emitRuntimeDecls().
        emit("");

        // Generate all top-level definitions (may populate m_globalStr)
        for (auto& s : prog.stmts)
            genTopLevel(s.get());

        // Final assembly order:
        //   1. target datalayout / target triple  (m_header)
        //   2. global string constants            (m_globalStr)
        //   3. runtime decls + forward decls + definitions  (m_out)
        std::string hdrPart    = m_header.str();
        std::string stringPart = m_globalStr.str();
        std::string bodyPart   = m_out.str();

        std::string result = hdrPart;
        if (!stringPart.empty()) result += stringPart + "\n";
        result += bodyPart;
        return result;
    }

private:
    std::ostringstream m_out;
    std::ostringstream m_globalStr;  // global string constants (inserted after header)
    std::ostringstream m_header;     // target datalayout / target triple (always first)

    Target m_target = Target::linux64();
    std::vector<Error> m_errors;

    // String literal dedup table: value → @str.N
    std::unordered_map<std::string, std::string> m_strings;
    int m_strCount  = 0;

    // Per-function state
    int m_tmpCount  = 0;
    int m_labelCount = 0;
    std::string m_funcRetType;
    // Local variable table: name → alloca pointer register (%name.addr)
    std::unordered_map<std::string, std::string> m_locals;
    // Current basic block label (for branch targets)
    std::string m_currentBlock;

    // -----------------------------------------------------------------------
    // Emission helpers
    // -----------------------------------------------------------------------
    void emit(const std::string& line) { m_out << line << "\n"; }
    void emitI(const std::string& line) { m_out << "  " << line << "\n"; } // indented
    void hdr(const std::string& line)  { m_header << line << "\n"; }  // module header

    std::string tmp()   { return "%t" + std::to_string(m_tmpCount++); }
    std::string label() { return "L" + std::to_string(m_labelCount++); }

    void error(const std::string& msg, int l=0, int c=0) {
        m_errors.push_back({msg, l, c});
    }

    // -----------------------------------------------------------------------
    // Type mapping: KonScript TypeAnnotation → LLVM IR type string
    // -----------------------------------------------------------------------
    std::string llvmType(const TypeAnnotation& t) {
        if (t.isArray)  return llvmType({t.base}) + "*"; // simplified: pointer
        if (t.isTuple)  return "{ " + [&]{ // struct literal
            std::string s;
            for (size_t i=0;i<t.tupleTypes.size();i++){
                if(i) s+=", ";
                s+=llvmType(t.tupleTypes[i]);
            }
            return s;
        }() + " }";
        if (t.nullable) return llvmType({t.base}) + "*"; // nullable → pointer

        const std::string& b = t.base;
        if (b=="I8"  || b=="Char") return "i8";
        if (b=="I16")              return "i16";
        if (b=="I32" || b=="Int")  return "i32";
        if (b=="I64" || b=="Long") return "i64";
        if (b=="U8")               return "i8";
        if (b=="U16")              return "i16";
        if (b=="U32" || b=="UInt") return "i32";
        if (b=="U64" || b=="ULong")return "i64";
        if (b=="F32" || b=="Float")return "float";
        if (b=="F64" || b=="Double")return "double";
        if (b=="Bool")             return "i1";
        if (b=="Str" || b=="String") return "i8*";
        if (b=="Void" || b=="()")  return "void";
        // User-defined struct/class — pointer to opaque type
        return "%struct." + b + "*";
    }

    std::string llvmTypeDefault(const TypeAnnotation& t) {
        // Zero/null default for a type
        std::string lt = llvmType(t);
        if (lt=="i1")   return "i1 false";
        if (lt=="i8")   return "i8 0";
        if (lt=="i16")  return "i16 0";
        if (lt=="i32")  return "i32 0";
        if (lt=="i64")  return "i64 0";
        if (lt=="float")  return "float 0.0";
        if (lt=="double") return "double 0.0";
        if (lt=="i8*")    return "i8* null";
        return lt + " null";
    }

    // -----------------------------------------------------------------------
    // Global string constant — returns i8* getelementptr to it
    // -----------------------------------------------------------------------
    std::string globalString(const std::string& value) {
        auto it = m_strings.find(value);
        if (it != m_strings.end()) return it->second;

        std::string name = "@str." + std::to_string(m_strCount++);
        // Escape the string for LLVM IR
        std::string escaped;
        for (unsigned char c : value) {
            if (c == '"')       escaped += "\\22";
            else if (c == '\\') escaped += "\\5C";
            else if (c == '\n') escaped += "\\0A";
            else if (c == '\t') escaped += "\\09";
            else if (c < 32 || c > 126) {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "\\%02X", c);
                escaped += buf;
            } else {
                escaped += c;
            }
        }
        int len = (int)value.size() + 1; // +1 for \00
        m_globalStr << name << " = private unnamed_addr constant ["
                    << len << " x i8] c\"" << escaped << "\\00\"\n";

        // The usable value is a getelementptr to i8*
        std::string ptrExpr = "getelementptr inbounds ([" + std::to_string(len)
            + " x i8], [" + std::to_string(len) + " x i8]* " + name
            + ", i32 0, i32 0)";
        m_strings[value] = ptrExpr;
        return ptrExpr;
    }

    // -----------------------------------------------------------------------
    // Runtime declarations
    // -----------------------------------------------------------------------
    void emitRuntimeDecls() {
        emit("; --- runtime ---");
        emit("declare i32 @printf(i8* nocapture, ...)");
        emit("declare i32 @scanf(i8* nocapture, ...)");
        emit("declare i8* @malloc(i64)");
        emit("declare void @free(i8*)");
        emit("declare double @sqrt(double)");
        emit("declare double @fabs(double)");
        emit("declare double @floor(double)");
        emit("declare double @ceil(double)");
        emit("declare i32 @strlen(i8*)");
        emit("declare i8* @strcpy(i8*, i8*)");
        emit("declare i8* @strcat(i8*, i8*)");
        emit("");
    }

    // -----------------------------------------------------------------------
    // Forward-declare a function so mutual calls work
    // -----------------------------------------------------------------------
    void forwardDeclareFunc(const FuncDecl* f) {
        std::string ret = f->returnType ? llvmType(*f->returnType) : "void";
        std::string sig = "declare " + ret + " @" + f->name + "(";
        for (size_t i = 0; i < f->params.size(); i++) {
            if (i) sig += ", ";
            sig += llvmType(f->params[i].type);
        }
        sig += ")";
        emit(sig);
    }

    // -----------------------------------------------------------------------
    // Top-level dispatch
    // -----------------------------------------------------------------------
    void genTopLevel(const Stmt* s) {
        switch (s->kind) {
        case Stmt::Kind::FuncDecl:
            genFunc(static_cast<const FuncDecl*>(s)); break;
        case Stmt::Kind::StructDecl:
            genStructType(static_cast<const StructDecl*>(s)); break;
        // Let/Const at top level → global variable
        case Stmt::Kind::Let:
        case Stmt::Kind::Const:
            genGlobal(s); break;
        // NodeDecl/ClassDecl → opaque struct + vtable (simplified: opaque ptr for now)
        case Stmt::Kind::NodeDecl:
            genNodeType(static_cast<const NodeDecl*>(s)); break;
        default: break;
        }
    }

    // -----------------------------------------------------------------------
    // Struct type
    // -----------------------------------------------------------------------
    void genStructType(const StructDecl* s) {
        std::string body = "{ ";
        for (size_t i = 0; i < s->fields.size(); i++) {
            if (i) body += ", ";
            body += llvmType(s->fields[i].type);
        }
        body += " }";
        emit("%struct." + s->name + " = type " + body);
    }

    // -----------------------------------------------------------------------
    // Node type — simplified: treat as opaque struct with vtable pointer
    // -----------------------------------------------------------------------
    void genNodeType(const NodeDecl* n) {
        emit("; node " + n->name + " (engine type, managed externally)");
        emit("%node." + n->name + " = type opaque");
        emit("");
        // Generate each method as a standalone function
        for (auto& m : n->methods) {
            // Synthetic first parameter: self pointer
            genNodeMethod(m.get(), n->name);
        }
    }

    void genNodeMethod(const FuncDecl* f, const std::string& nodeName) {
        // Prepend implicit self: %node.NodeName*
        std::string ret = f->returnType ? llvmType(*f->returnType) : "void";
        std::string fname = nodeName + "__" + f->name;

        emit("define " + ret + " @" + fname + "(%node." + nodeName + "* %self" +
             (f->params.empty() ? "" : ", ") +
             [&]{
                 std::string s;
                 for (size_t i=0;i<f->params.size();i++){
                     if(i) s+=", ";
                     s += llvmType(f->params[i].type) + " %" + f->params[i].name;
                 }
                 return s;
             }() + ") {");
        emit("entry:");
        m_funcRetType = ret;
        m_tmpCount = 0;
        m_labelCount = 0;
        m_currentBlock = "entry";
        m_locals.clear();
        // Alloca params
        for (auto& p : f->params) allocaParam(p.name, p.type);
        genBlock(f->body.get());
        // Ensure terminator
        emitReturnDefault(ret);
        emit("}");
        emit("");
    }

    // -----------------------------------------------------------------------
    // Global variable (top-level let/const)
    // -----------------------------------------------------------------------
    void genGlobal(const Stmt* s) {
        // For simplicity: emit as a global with a constant initializer.
        // Expressions that require runtime init are put in @__ks_init.
        if (s->kind == Stmt::Kind::Let) {
            auto* l = static_cast<const LetStmt*>(s);
            std::string lt = llvmType(l->type);
            // Only constant initializers are valid here; runtime ones need a ctor
            if (l->init && l->init->kind == Expr::Kind::IntLit) {
                auto* v = static_cast<const IntLitExpr*>(l->init.get());
                emit("@" + l->name + " = global " + lt + " " + std::to_string(v->value));
            } else if (l->init && l->init->kind == Expr::Kind::FloatLit) {
                auto* v = static_cast<const FloatLitExpr*>(l->init.get());
                emit("@" + l->name + " = global " + lt + " " + std::to_string(v->value));
            } else if (l->init && l->init->kind == Expr::Kind::BoolLit) {
                auto* v = static_cast<const BoolLitExpr*>(l->init.get());
                emit("@" + l->name + " = global i1 " + (v->value ? "true" : "false"));
            } else {
                // Zero-init, runtime init handled in @__ks_init
                emit("@" + l->name + " = global " + lt + " zeroinitializer");
            }
        } else {
            auto* c = static_cast<const ConstStmt*>(s);
            std::string lt = llvmType(c->type);
            if (c->init && c->init->kind == Expr::Kind::IntLit) {
                auto* v = static_cast<const IntLitExpr*>(c->init.get());
                emit("@" + c->name + " = constant " + lt + " " + std::to_string(v->value));
            } else {
                emit("@" + c->name + " = constant " + lt + " zeroinitializer");
            }
        }
    }

    // -----------------------------------------------------------------------
    // Function
    // -----------------------------------------------------------------------
    void genFunc(const FuncDecl* f) {
        std::string ret = f->returnType ? llvmType(*f->returnType) : "void";
        m_funcRetType   = ret;
        m_tmpCount      = 0;
        m_labelCount    = 0;
        m_currentBlock  = "entry";
        m_locals.clear();

        // Build parameter list
        std::string params;
        for (size_t i = 0; i < f->params.size(); i++) {
            if (i) params += ", ";
            params += llvmType(f->params[i].type) + " %" + f->params[i].name + ".arg";
        }

        // Use define linkage (not declare — we have a body)
        std::string linkage = f->pub ? "" : "internal ";
        // Special case: main() must be i32 and public
        if (f->name == "main") {
            emit("define i32 @main() {");
        } else {
            emit("define " + linkage + ret + " @" + f->name + "(" + params + ") {");
        }
        emit("entry:");

        // Alloca for each parameter so they can be addressed by name
        for (auto& p : f->params)
            allocaParam(p.name, p.type);

        // Store parameter values into their allocas
        for (auto& p : f->params) {
            std::string lt = llvmType(p.type);
            emitI("store " + lt + " %" + p.name + ".arg, " + lt + "* %" + p.name + ".addr");
        }

        // Body
        genBlock(f->body.get());

        // Auto-add return if the function didn't end with one
        if (f->name == "main") {
            emitI("ret i32 0");
        } else {
            emitReturnDefault(ret);
        }

        emit("}");
        emit("");
    }

    // -----------------------------------------------------------------------
    // Alloca helper — allocates stack space for a local variable
    // -----------------------------------------------------------------------
    void allocaParam(const std::string& name, const TypeAnnotation& type) {
        std::string lt  = llvmType(type);
        std::string reg = "%" + name + ".addr";
        emitI(reg + " = alloca " + lt);
        m_locals[name] = reg;
    }

    void allocaLocal(const std::string& name, const TypeAnnotation& type) {
        std::string lt  = llvmType(type);
        std::string reg = "%" + name + ".addr";
        emitI(reg + " = alloca " + lt);
        m_locals[name] = reg;
    }

    // Load a local variable into a fresh temp register; returns "%tN"
    std::string loadLocal(const std::string& name, const TypeAnnotation& type) {
        auto it = m_locals.find(name);
        if (it == m_locals.end()) {
            // May be a global
            std::string t  = tmp();
            std::string lt = llvmType(type);
            emitI(t + " = load " + lt + ", " + lt + "* @" + name);
            return t;
        }
        std::string t  = tmp();
        std::string lt = llvmType(type);
        emitI(t + " = load " + lt + ", " + lt + "* " + it->second);
        return t;
    }

    // -----------------------------------------------------------------------
    // Ensure the current block has a terminator (avoids invalid IR)
    // -----------------------------------------------------------------------
    void emitReturnDefault(const std::string& retType) {
        if (retType == "void") emitI("ret void");
        else if (retType == "i1")    emitI("ret i1 false");
        else if (retType == "i32")   emitI("ret i32 0");
        else if (retType == "i64")   emitI("ret i64 0");
        else if (retType == "float") emitI("ret float 0.0");
        else if (retType == "double")emitI("ret double 0.0");
        else if (retType == "i8*")   emitI("ret i8* null");
        else                         emitI("ret " + retType + " undef");
    }

    // -----------------------------------------------------------------------
    // Block / statement dispatch
    // -----------------------------------------------------------------------
    void genBlock(const BlockStmt* b) {
        if (!b) return;
        for (auto& s : b->stmts) genStmt(s.get());
    }

    void genStmt(const Stmt* s) {
        if (!s) return;
        switch (s->kind) {
        case Stmt::Kind::Let:      genLet(s);       break;
        case Stmt::Kind::Const:    genConst(s);     break;
        case Stmt::Kind::ExprStmt: genExprStmt(s);  break;
        case Stmt::Kind::Return:   genReturn(s);    break;
        case Stmt::Kind::If:       genIf(s);        break;
        case Stmt::Kind::While:    genWhile(s);     break;
        case Stmt::Kind::Loop:     genLoopStmt(s);  break;
        case Stmt::Kind::ForC:     genForC(s);      break;
        case Stmt::Kind::ForIn:    genForIn(s);     break;
        case Stmt::Kind::Break:    emitI("br label %__break"); break; // fixed up by loop codegen
        case Stmt::Kind::Continue: emitI("br label %__cont");  break;
        case Stmt::Kind::Block: {
            auto* blk = static_cast<const BlockStmt*>(s);
            genBlock(blk);
            break;
        }
        case Stmt::Kind::FuncDecl:
            // Nested function — emit as a separate function (closure not supported yet)
            genFunc(static_cast<const FuncDecl*>(s));
            break;
        default: break;
        }
    }

    // -----------------------------------------------------------------------
    // let / const
    // -----------------------------------------------------------------------
    void genLet(const Stmt* s) {
        auto* l = static_cast<const LetStmt*>(s);
        allocaLocal(l->name, l->type);
        if (l->init) {
            auto [val, lt] = genExpr(l->init.get(), l->type);
            emitI("store " + lt + " " + val + ", " + lt + "* %" + l->name + ".addr");
        }
    }
    void genConst(const Stmt* s) {
        auto* c = static_cast<const ConstStmt*>(s);
        allocaLocal(c->name, c->type);
        if (c->init) {
            auto [val, lt] = genExpr(c->init.get(), c->type);
            emitI("store " + lt + " " + val + ", " + lt + "* %" + c->name + ".addr");
        }
    }

    // -----------------------------------------------------------------------
    // Expression statement
    // -----------------------------------------------------------------------
    void genExprStmt(const Stmt* s) {
        auto* e = static_cast<const ExprStmt*>(s);
        genExpr(e->expr.get());
    }

    // -----------------------------------------------------------------------
    // Return
    // -----------------------------------------------------------------------
    void genReturn(const Stmt* s) {
        auto* r = static_cast<const ReturnStmt*>(s);
        if (!r->value || m_funcRetType == "void") {
            emitI("ret void");
        } else {
            auto [val, lt] = genExpr(r->value.get());
            emitI("ret " + lt + " " + val);
        }
    }

    // -----------------------------------------------------------------------
    // If / else
    // -----------------------------------------------------------------------
    void genIf(const Stmt* s) {
        auto* i   = static_cast<const IfStmt*>(s);
        std::string thenL = label(), elseL = label(), endL = label();

        auto [cond, _] = genExpr(i->cond.get());
        if (i->else_) {
            emitI("br i1 " + cond + ", label %" + thenL + ", label %" + elseL);
        } else {
            emitI("br i1 " + cond + ", label %" + thenL + ", label %" + endL);
        }

        emit(thenL + ":");
        m_currentBlock = thenL;
        genBlock(i->then_.get());
        emitI("br label %" + endL);

        if (i->else_) {
            emit(elseL + ":");
            m_currentBlock = elseL;
            genBlock(i->else_.get());
            emitI("br label %" + endL);
        }

        emit(endL + ":");
        m_currentBlock = endL;
    }

    // -----------------------------------------------------------------------
    // While loop
    // -----------------------------------------------------------------------
    void genWhile(const Stmt* s) {
        auto* w   = static_cast<const WhileStmt*>(s);
        std::string condL = label(), bodyL = label(), endL = label();

        emitI("br label %" + condL);
        emit(condL + ":");
        m_currentBlock = condL;

        auto [cond, _] = genExpr(w->cond.get());
        emitI("br i1 " + cond + ", label %" + bodyL + ", label %" + endL);

        emit(bodyL + ":");
        m_currentBlock = bodyL;
        genBlock(w->body.get());
        emitI("br label %" + condL);

        emit(endL + ":");
        m_currentBlock = endL;
    }

    // -----------------------------------------------------------------------
    // Infinite loop
    // -----------------------------------------------------------------------
    void genLoopStmt(const Stmt* s) {
        auto* l = static_cast<const LoopStmt*>(s);
        std::string bodyL = label(), endL = label();
        emitI("br label %" + bodyL);
        emit(bodyL + ":");
        m_currentBlock = bodyL;
        genBlock(l->body.get());
        emitI("br label %" + bodyL);
        emit(endL + ":");
        m_currentBlock = endL;
    }

    // -----------------------------------------------------------------------
    // for i: I32 = init; cond; step
    // -----------------------------------------------------------------------
    void genForC(const Stmt* s) {
        auto* f   = static_cast<const ForCStmt*>(s);
        std::string initL = label(), condL = label(), bodyL = label(),
                    stepL = label(), endL  = label();

        // Init
        allocaLocal(f->var, f->type);
        auto [initVal, lt] = genExpr(f->init.get(), f->type);
        emitI("store " + lt + " " + initVal + ", " + lt + "* %" + f->var + ".addr");

        emitI("br label %" + condL);
        emit(condL + ":");
        m_currentBlock = condL;
        auto [cond, _] = genExpr(f->cond.get());
        emitI("br i1 " + cond + ", label %" + bodyL + ", label %" + endL);

        emit(bodyL + ":");
        m_currentBlock = bodyL;
        genBlock(f->body.get());
        emitI("br label %" + stepL);

        emit(stepL + ":");
        m_currentBlock = stepL;
        genExpr(f->step.get());
        emitI("br label %" + condL);

        emit(endL + ":");
        m_currentBlock = endL;
    }

    // -----------------------------------------------------------------------
    // for x: T in iterable  (range 0..N only for now, arrays TBD)
    // -----------------------------------------------------------------------
    void genForIn(const Stmt* s) {
        auto* f = static_cast<const ForInStmt*>(s);

        // Only handle integer range (0..N or 0..=N) for now
        if (f->iterable->kind == Expr::Kind::Range) {
            auto* r = static_cast<const RangeExpr*>(f->iterable.get());
            std::string condL = label(), bodyL = label(),
                        stepL = label(), endL  = label();

            allocaLocal(f->var, f->type);
            auto [start, slt] = genExpr(r->from.get(), f->type);
            emitI("store " + slt + " " + start + ", " + slt + "* %" + f->var + ".addr");

            emitI("br label %" + condL);
            emit(condL + ":");
            m_currentBlock = condL;
            std::string cur = tmp();
            emitI(cur + " = load " + slt + ", " + slt + "* %" + f->var + ".addr");
            auto [end, elt] = genExpr(r->to.get(), f->type);
            std::string cond = tmp();
            std::string cmp  = r->inclusive ? "sle" : "slt";
            emitI(cond + " = icmp " + cmp + " " + slt + " " + cur + ", " + end);
            emitI("br i1 " + cond + ", label %" + bodyL + ", label %" + endL);

            emit(bodyL + ":");
            m_currentBlock = bodyL;
            genBlock(f->body.get());
            emitI("br label %" + stepL);

            emit(stepL + ":");
            m_currentBlock = stepL;
            std::string curi = tmp();
            emitI(curi + " = load " + slt + ", " + slt + "* %" + f->var + ".addr");
            std::string next = tmp();
            emitI(next + " = add " + slt + " " + curi + ", 1");
            emitI("store " + slt + " " + next + ", " + slt + "* %" + f->var + ".addr");
            emitI("br label %" + condL);

            emit(endL + ":");
            m_currentBlock = endL;
        } else {
            error("for-in over non-range iterables not yet supported in IRGen",
                  f->line, f->col);
        }
    }

    // -----------------------------------------------------------------------
    // Expressions — returns {register_or_constant, llvm_type_string}
    // The hint type is used when we need to coerce (e.g. int literal to i64)
    // -----------------------------------------------------------------------
    using ValType = std::pair<std::string, std::string>;

    ValType genExpr(const Expr* e, const TypeAnnotation& hint = {}) {
        if (!e) return {"undef", "i32"};
        switch (e->kind) {
        case Expr::Kind::IntLit:   return genIntLit(static_cast<const IntLitExpr*>(e), hint);
        case Expr::Kind::FloatLit: return genFloatLit(static_cast<const FloatLitExpr*>(e), hint);
        case Expr::Kind::BoolLit: {
            auto* b = static_cast<const BoolLitExpr*>(e);
            return {b->value ? "true" : "false", "i1"};
        }
        case Expr::Kind::StrLit: {
            auto* sl = static_cast<const StrLitExpr*>(e);
            return {globalString(sl->value), "i8*"};
        }
        case Expr::Kind::NullLit:
        case Expr::Kind::NoneLit:
            return {"null", "i8*"};

        case Expr::Kind::Ident:    return genIdent(static_cast<const IdentExpr*>(e));
        case Expr::Kind::Unary:    return genUnary(static_cast<const UnaryExpr*>(e));
        case Expr::Kind::Binary:   return genBinary(static_cast<const BinaryExpr*>(e));
        case Expr::Kind::Assign:   return genAssign(static_cast<const AssignExpr*>(e));
        case Expr::Kind::Call:     return genCall(static_cast<const CallExpr*>(e));
        case Expr::Kind::Member:   return genMember(static_cast<const MemberExpr*>(e));
        case Expr::Kind::Cast:     return genCast(static_cast<const CastExpr*>(e));
        case Expr::Kind::Index:    return genIndex(static_cast<const IndexExpr*>(e));
        default:
            error("IRGen: unsupported expression kind " + std::to_string((int)e->kind),
                  e->line, e->col);
            return {"undef", "i32"};
        }
    }

    ValType genIntLit(const IntLitExpr* e, const TypeAnnotation& hint) {
        std::string lt = hint.base.empty() ? "i32" : llvmType(hint);
        return {std::to_string(e->value), lt};
    }

    ValType genFloatLit(const FloatLitExpr* e, const TypeAnnotation& hint) {
        std::string lt = (hint.base == "F32" || hint.base == "Float") ? "float" : "double";
        return {std::to_string(e->value), lt};
    }

    ValType genIdent(const IdentExpr* e) {
        // Known built-in constants
        if (e->name == "true")  return {"true",  "i1"};
        if (e->name == "false") return {"false", "i1"};
        if (e->name == "null")  return {"null",  "i8*"};

        auto it = m_locals.find(e->name);
        if (it != m_locals.end()) {
            // We don't know the type here without the symbol table.
            // Emit a load using i32 as a fallback — the typechecker pass should
            // have validated types already.
            // TODO: carry type info in locals table
            std::string t = tmp();
            emitI(t + " = load i32, i32* " + it->second + "  ; " + e->name);
            return {t, "i32"};
        }
        // Global variable
        std::string t = tmp();
        emitI(t + " = load i32, i32* @" + e->name + "  ; global");
        return {t, "i32"};
    }

    ValType genUnary(const UnaryExpr* e) {
        auto [val, lt] = genExpr(e->operand.get());
        if (e->op == "-") {
            std::string t = tmp();
            if (lt == "float" || lt == "double")
                emitI(t + " = fneg " + lt + " " + val);
            else
                emitI(t + " = sub " + lt + " 0, " + val);
            return {t, lt};
        }
        if (e->op == "!") {
            std::string t = tmp();
            emitI(t + " = xor i1 " + val + ", true");
            return {t, "i1"};
        }
        if (e->op == "++" || e->op == "--") {
            // Only works on idents (lvalue)
            if (e->operand->kind == Expr::Kind::Ident) {
                auto* id = static_cast<const IdentExpr*>(e->operand.get());
                auto addr = m_locals.count(id->name) ? m_locals[id->name] : "@" + id->name;
                std::string old = tmp();
                emitI(old + " = load " + lt + ", " + lt + "* " + addr);
                std::string nxt = tmp();
                std::string op  = (e->op == "++") ? "add" : "sub";
                emitI(nxt + " = " + op + " " + lt + " " + old + ", 1");
                emitI("store " + lt + " " + nxt + ", " + lt + "* " + addr);
                return {e->postfix ? old : nxt, lt};
            }
        }
        return {val, lt};
    }

    ValType genBinary(const BinaryExpr* e) {
        auto [lv, lt] = genExpr(e->left.get());
        auto [rv, rt] = genExpr(e->right.get());

        // Use left type as authoritative
        std::string t = tmp();
        bool isFloat = (lt == "float" || lt == "double");
        bool isBool  = false;

        std::string op = e->op;
        if (op == "+")  { emitI(t + " = " + (isFloat?"fadd":"add") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "-") { emitI(t + " = " + (isFloat?"fsub":"sub") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "*") { emitI(t + " = " + (isFloat?"fmul":"mul") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "/") { emitI(t + " = " + (isFloat?"fdiv":"sdiv") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "%") { emitI(t + " = " + (isFloat?"frem":"srem") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "==") { isBool=true; emitI(t + " = " + (isFloat?"fcmp oeq":"icmp eq") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "!=") { isBool=true; emitI(t + " = " + (isFloat?"fcmp one":"icmp ne") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "<")  { isBool=true; emitI(t + " = " + (isFloat?"fcmp olt":"icmp slt") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "<=") { isBool=true; emitI(t + " = " + (isFloat?"fcmp ole":"icmp sle") + " " + lt + " " + lv + ", " + rv); }
        else if (op == ">")  { isBool=true; emitI(t + " = " + (isFloat?"fcmp ogt":"icmp sgt") + " " + lt + " " + lv + ", " + rv); }
        else if (op == ">=") { isBool=true; emitI(t + " = " + (isFloat?"fcmp oge":"icmp sge") + " " + lt + " " + lv + ", " + rv); }
        else if (op == "&&") { isBool=true; emitI(t + " = and i1 " + lv + ", " + rv); }
        else if (op == "||") { isBool=true; emitI(t + " = or i1 " + lv + ", " + rv); }
        else if (op == "&")  { emitI(t + " = and " + lt + " " + lv + ", " + rv); }
        else if (op == "|")  { emitI(t + " = or " + lt + " " + lv + ", " + rv); }
        else if (op == "^")  { emitI(t + " = xor " + lt + " " + lv + ", " + rv); }
        else if (op == "<<") { emitI(t + " = shl " + lt + " " + lv + ", " + rv); }
        else if (op == ">>") { emitI(t + " = ashr " + lt + " " + lv + ", " + rv); }
        else {
            error("IRGen: unsupported binary op: " + op, e->line, e->col);
            emitI(t + " = add i32 0, 0");
        }

        return {t, isBool ? "i1" : lt};
    }

    ValType genAssign(const AssignExpr* e) {
        auto [val, lt] = genExpr(e->value.get());

        // Find the lvalue address
        std::string addr;
        if (e->target->kind == Expr::Kind::Ident) {
            auto* id = static_cast<const IdentExpr*>(e->target.get());
            auto it = m_locals.find(id->name);
            addr = (it != m_locals.end()) ? it->second : "@" + id->name;
        } else {
            error("IRGen: complex lvalue assignment not yet supported", e->line, e->col);
            return {val, lt};
        }

        // Handle compound assignments (+=, -=, etc.)
        std::string finalVal = val;
        if (e->op != "=") {
            std::string old = tmp();
            emitI(old + " = load " + lt + ", " + lt + "* " + addr);
            std::string t   = tmp();
            bool isFloat = (lt == "float" || lt == "double");
            if      (e->op == "+=") emitI(t + " = " + (isFloat?"fadd":"add") + " " + lt + " " + old + ", " + val);
            else if (e->op == "-=") emitI(t + " = " + (isFloat?"fsub":"sub") + " " + lt + " " + old + ", " + val);
            else if (e->op == "*=") emitI(t + " = " + (isFloat?"fmul":"mul") + " " + lt + " " + old + ", " + val);
            else if (e->op == "/=") emitI(t + " = " + (isFloat?"fdiv":"sdiv") + " " + lt + " " + old + ", " + val);
            finalVal = t;
        }

        emitI("store " + lt + " " + finalVal + ", " + lt + "* " + addr);
        return {finalVal, lt};
    }

    // -----------------------------------------------------------------------
    // Function call — handles Print, ToString builtins + user functions
    // -----------------------------------------------------------------------
    ValType genCall(const CallExpr* e) {
        // Get callee name
        std::string callee;
        if (e->callee->kind == Expr::Kind::Ident)
            callee = static_cast<const IdentExpr*>(e->callee.get())->name;

        // ---- Print(x, y, ...) → printf with format string ----
        if (callee == "Print") {
            std::string fmt;
            std::vector<std::string> args;
            std::vector<std::string> argTypes;
            for (auto& arg : e->args) {
                auto [v, t] = genExpr(arg.get());
                args.push_back(v);
                argTypes.push_back(t);
                if      (t == "i32" || t == "i16" || t == "i8") fmt += "%d";
                else if (t == "i64")    fmt += "%lld";
                else if (t == "float")  fmt += "%f";
                else if (t == "double") fmt += "%lf";
                else if (t == "i1")     fmt += "%d";
                else if (t == "i8*")    fmt += "%s";
                else                    fmt += "%p";
            }
            fmt += "\n";
            std::string fmtPtr = globalString(fmt);
            std::string argStr;
            for (size_t i = 0; i < args.size(); i++) {
                argStr += ", " + argTypes[i] + " " + args[i];
            }
            std::string t = tmp();
            emitI(t + " = call i32 (i8*, ...) @printf(i8* " + fmtPtr + argStr + ")");
            return {t, "i32"};
        }

        // ---- ToString(x) → sprintf into a buffer (simplified: return the number as string) ----
        if (callee == "ToString" && e->args.size() == 1) {
            auto [v, t] = genExpr(e->args[0].get());
            std::string buf = tmp();
            emitI(buf + " = alloca [32 x i8]");
            std::string ptr = tmp();
            emitI(ptr + " = getelementptr inbounds [32 x i8], [32 x i8]* " + buf + ", i32 0, i32 0");
            std::string fmt = (t == "double" || t == "float") ? "%lf" : "%d";
            std::string fmtPtr = globalString(fmt);
            emitI("call i32 (i8*, i8*, ...) @sprintf(i8* " + ptr + ", i8* " + fmtPtr + ", " + t + " " + v + ")");
            return {ptr, "i8*"};
        }

        // ---- Regular user-defined function call ----
        std::vector<std::string> argParts;
        for (auto& arg : e->args) {
            auto [v, t] = genExpr(arg.get());
            argParts.push_back(t + " " + v);
        }
        std::string argList;
        for (size_t i = 0; i < argParts.size(); i++) {
            if (i) argList += ", ";
            argList += argParts[i];
        }

        // For simplicity assume i32 return — proper type info comes from symbol table
        std::string t = tmp();
        emitI(t + " = call i32 @" + callee + "(" + argList + ")");
        return {t, "i32"};
    }

    // -----------------------------------------------------------------------
    // Member access — simplified (struct GEP)
    // -----------------------------------------------------------------------
    ValType genMember(const MemberExpr* e) {
        // For now, emit a comment and return undef
        // Full struct GEP requires the struct layout from the type checker
        std::string t = tmp();
        emitI(t + " = add i32 0, 0  ; TODO: member " + e->member);
        return {t, "i32"};
    }

    // -----------------------------------------------------------------------
    // Cast (as)
    // -----------------------------------------------------------------------
    ValType genCast(const CastExpr* e) {
        auto [val, from] = genExpr(e->value.get());
        std::string to   = llvmType(e->target);
        std::string t    = tmp();

        bool fromFloat = (from == "float" || from == "double");
        bool toFloat   = (to   == "float" || to   == "double");
        bool fromInt   = !fromFloat && from != "i1" && from != "i8*";
        bool toInt     = !toFloat   && to   != "i1" && to   != "i8*";

        if      (fromFloat && toInt)   emitI(t + " = fptosi " + from + " " + val + " to " + to);
        else if (fromInt   && toFloat) emitI(t + " = sitofp " + from + " " + val + " to " + to);
        else if (fromFloat && toFloat) emitI(t + " = fpext "  + from + " " + val + " to " + to);
        else if (fromInt   && toInt)   emitI(t + " = sext "   + from + " " + val + " to " + to);
        else if (from == "i1" && toInt) emitI(t + " = zext i1 " + val + " to " + to);
        else {
            // Best effort bitcast
            emitI(t + " = bitcast " + from + " " + val + " to " + to);
        }
        return {t, to};
    }

    // -----------------------------------------------------------------------
    // Array index
    // -----------------------------------------------------------------------
    ValType genIndex(const IndexExpr* e) {
        auto [base, _] = genExpr(e->object.get());
        auto [idx,  __] = genExpr(e->index.get());
        std::string ptr = tmp();
        // Treat as i32* array — full type from symbol table needed for correctness
        emitI(ptr + " = getelementptr i32, i32* " + base + ", i32 " + idx);
        std::string val = tmp();
        emitI(val + " = load i32, i32* " + ptr);
        return {val, "i32"};
    }
};

} // namespace KonScript
