#include "ProjectManager.hpp"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QJsonObject>
#include <QDateTime>
#include <QTextStream>

ProjectManager::ProjectManager(QObject* parent) : QObject(parent) {}

bool ProjectManager::create(const QString& dir) {
    QDir d(dir);
    QString name = d.dirName();
    if (name.isEmpty()) name = "MyGame";

    // Create folder structure
    d.mkpath("src");
    d.mkpath("assets");
    d.mkpath("build");
    d.mkpath("scenes");

    // Write starter main.ks
    QString mainKs = dir + "/src/main.ks";
    if (!QFile::exists(mainKs)) {
        QFile f(mainKs);
        if (f.open(QIODevice::WriteOnly | QIODevice::Text)) {
            QString src =
                "#include <engine>\n"
                "#include \"../scenes/Main.ks\"\n"
                "\n"
                "func main() {\n"
                "    InitWindow(800, 600, \"" + name + "\");\n"
                "    SetTargetFPS(60);\n"
                "    SetVsync(true);\n"
                "\n"
                "    let mut scene: Scene = Scene();\n"
                "    scene.add(Main, \"Main\");\n"
                "\n"
                "    while !WindowShouldClose() {\n"
                "        scene.update(GetDeltaTime());\n"
                "        ClearBackground(0.1, 0.1, 0.15);\n"
                "        scene.draw();\n"
                "        Present();\n"
                "        PollEvents();\n"
                "    }\n"
                "}\n";
            f.write(src.toUtf8());
            f.close();
        }
    }

    // Write starter scenes/Main.ks
    QString mainScene = dir + "/scenes/Main.ks";
    if (!QFile::exists(mainScene)) {
        QFile sf(mainScene);
        if (sf.open(QIODevice::WriteOnly | QIODevice::Text)) {
            sf.write(
                "# Main.ks -- generated by KonEditor\n"
                "#include <engine>\n"
                "\n"
                "node Main : Node2D {\n"
                "    func Ready() {\n"
                "    }\n"
                "}\n"
            );
            sf.flush();
            sf.close();
        }
    }

    m_name      = name;
    m_rootDir   = dir;
    m_path      = dir + "/" + name + ".konproj";
    m_entryFile = dir + "/src/main.ks";
    m_open      = true;

    m_json["name"]    = name;
    m_json["version"] = QString("0.1.0");
    m_json["entry"]   = QString("src/main.ks");
    m_json["created"] = QDateTime::currentDateTime().toString(Qt::ISODate);

    return save();
}

bool ProjectManager::open(const QString& konprojPath) {
    QFile f(konprojPath);
    if (!f.open(QIODevice::ReadOnly)) return false;
    auto doc = QJsonDocument::fromJson(f.readAll());
    if (doc.isNull() || !doc.isObject()) return false;
    m_json      = doc.object();
    m_path      = konprojPath;
    m_rootDir   = QFileInfo(konprojPath).absolutePath();
    m_name      = m_json.value("name").toString("Untitled");
    QString entry = m_json.value("entry").toString("src/main.ks");
    m_entryFile = m_rootDir + "/" + entry;
    m_open      = true;
    return true;
}

bool ProjectManager::save() {
    if (!m_open) return false;
    QFile f(m_path);
    if (!f.open(QIODevice::WriteOnly)) return false;
    f.write(QJsonDocument(m_json).toJson(QJsonDocument::Indented));
    return true;
}
