// Generated by KonScript v0.1.0 -- do not edit
// Source: /home/delta/testingground/TestGame/KonEngine/tests/test_game.ks
#include "KonEngine.hpp"
#include <cstdio>
#include <cmath>
#include <string>
#include <vector>
#include <functional>
#include <iostream>
#include <sstream>
#include <optional>
namespace { struct _KSInit {
    _KSInit() { std::cout << std::boolalpha; }
} _ks_init; }

class Player;
class Wall;
class Box;

class Player : public Sprite2D {
public:
    Player(const std::string& _name) : Sprite2D(_name) {
        anim = this->AddChild<AnimationPlayer>("anim");
    }
    
    float velX = 0.0f;
    float velY = 0.0f;
    bool grounded = false;
    float speed = 220.0f;
    float gravity = 900.0f;
    int32_t hits = 0;
    AnimationPlayer* anim;
    
    void Ready() override {
        x = 120.0f;
        y = 400.0f;
        originX = 0.5f;
        originY = 1.0f;
        scaleX = 2.0f;
        scaleY = 2.0f;
        Collider2D* col = this->AddChild<Collider2D>("playerCol");
        col->width = 28.0f;
        col->height = 48.0f;
        col->x = 0.0f;
        col->y = -24.0f;
        anim->LoadFromFile("player.konani");
        anim->Play("idle");
        std::cout << "[TestGame] Player Ready\n" << "\n";
    }
    
    void Update(float dt) override {
        velX = 0.0f;
        if (IsKeyDown((Key::Code)(Key::D))) {
            velX = speed;
            scaleX = 2.0f;
        }
        if (IsKeyDown((Key::Code)(Key::A))) {
            velX = -speed;
            scaleX = -2.0f;
        }
        x += (velX * dt);
        if ((IsKeyPressed((Key::Code)(Key::Space)) && grounded)) {
            velY = -500.0f;
            grounded = false;
        }
        velY += (gravity * dt);
        y += (velY * dt);
        if ((y >= 500.0f)) {
            y = 500.0f;
            velY = 0.0f;
            grounded = true;
        }
        if ((x < 0.0f)) {
            x = 0.0f;
        }
        if ((x > 800.0f)) {
            x = 800.0f;
        }
        if (grounded) {
            if ((velX != 0.0f)) {
                anim->Play("walk");
            } else {
                anim->Play("idle");
            }
        }
        DrawText((const char*)"WASD:move  Space:jump", (float)10, (float)10, (int)14, WHITE);
        { char _ks_buf[512]; snprintf(_ks_buf, sizeof(_ks_buf), "Collisions: %d", hits); DrawText(_ks_buf, (float)10, (float)28, (int)14, YELLOW); };
        DrawText((const char*)"Press ESC to quit", (float)10, (float)46, (int)14, GRAY);
    }
    
    void OnCollisionEnter(Collider2D* other) override {
        hits += 1;
        std::cout << "[Collision] Player hit %s  total=%d\n" << " " << other->name << " " << hits << "\n";
    }
    
    void OnCollisionExit(Collider2D* other) override {
        std::cout << "[Collision] Player left %s\n" << " " << other->name << "\n";
    }
    
};

class Wall : public Node2D {
public:
    Wall(const std::string& _name) : Node2D(_name) {
        col = this->AddChild<Collider2D>("wallCol");
    }
    
    float w = 80.0f;
    float h = 300.0f;
    Collider2D* col;
    
    void Ready() override {
        col->width = w;
        col->height = h;
        std::cout << "[TestGame] Wall Ready  col=%fx%f\n" << " " << col->width << " " << col->height << "\n";
    }
    
    void Draw() override {
        DrawRectangle((x - (w * 0.5f)), (y - (h * 0.5f)), w, h, ORANGE);
        DrawRectangle((x - (w * 0.5f)), (y - (h * 0.5f)), w, 3.0f, RED);
    }
    
};

class Box : public Node2D {
public:
    Box(const std::string& _name) : Node2D(_name) {
        col = this->AddChild<Collider2D>("boxCol");
    }
    
    float size = 40.0f;
    Collider2D* col;
    
    void Ready() override {
        col->width = size;
        col->height = size;
    }
    
    void Draw() override {
        DrawRectangle((x - (size * 0.5f)), (y - (size * 0.5f)), size, size, CYAN);
    }
    
};

int main() {
    InitWindow(800, 600, "KonEngine -- KonScript Test Game");
    SetTargetFPS(60);
    DebugMode(true);
    Texture tex = LoadTexture("player.png");
    Scene scene = Scene();
    Player* player = scene.Add<Player>("player");
    player->SetTexture(tex);
    Wall* wall = scene.Add<Wall>("wall");
    wall->x = 600.0f;
    wall->y = 350.0f;
    scene.Scan();
    Camera2D cam = Camera2D(400.0f, 300.0f, 1.0f, 0.0f);
    int32_t boxCount = 0;
    std::cout << "[TestGame] All nodes Ready\n" << "\n";
    while (!WindowShouldClose()) {
        const float dt = GetDeltaTime();
        if (IsKeyPressed((Key::Code)(Key::Escape))) {
            break;
        }
        if (IsMouseButtonPressed(Mouse::Left)) {
            boxCount += 1;
            Box* box = scene.Add<Box>("box");
            box->x = GetWorldMouseX(cam);
            box->y = GetWorldMouseY(cam);
            scene.Scan();
        }
        if (IsMouseButtonPressed(Mouse::Right)) {
            for (int32_t i = 0; i < boxCount; i++) {
                scene.Remove("box");
            }
            boxCount = 0;
            scene.Scan();
        }
        const float scroll = GetMouseScroll();
        if ((scroll != 0.0f)) {
            const float z = (cam.zoom + (scroll * 0.1f));
            if ((z < 0.1f)) {
                cam = Camera2D(cam.x, cam.y, 0.1f, cam.rotation);
            }
            if ((z > 5.0f)) {
                cam = Camera2D(cam.x, cam.y, 5.0f, cam.rotation);
            }
        }
        ClearBackground(0.08f, 0.08f, 0.12f);
        BeginCamera2D(cam);
        scene.Update(dt);
        scene.Draw();
        DrawLine(0.0f, 500.0f, 800.0f, 500.0f, GRAY);
        EndCamera2D();
        { char _ks_buf[512]; snprintf(_ks_buf, sizeof(_ks_buf), "FPS: %d", GetFPS()); DrawText(_ks_buf, (float)10, (float)580, (int)12, GREEN); };
        { char _ks_buf[512]; snprintf(_ks_buf, sizeof(_ks_buf), "Boxes: %d  (LClick=add  RClick=clear)", boxCount); DrawText(_ks_buf, (float)10, (float)565, (int)12, GRAY); };
        Present();
        PollEvents();
    }
}

