// Generated by KonScript v0.1.0 -- do not edit
// Source: tests/test_for_range.ks
#include <string>
#include <vector>
#include <functional>
#include <iostream>
#include <sstream>
#include <optional>
#include <fstream>
#include <unordered_map>
#include <algorithm>
#include <cstdint>
#include <tuple>
#ifndef _KS_STDLIB_HELPERS_DEFINED
#define _KS_STDLIB_HELPERS_DEFINED
template<typename T>
struct _KsResult {
    bool        ok    = false;
    T           value = {};
    std::string error;
    static _KsResult<T> Ok(T v) { _KsResult<T> r; r.ok=true;  r.value=std::move(v); return r; }
    static _KsResult<T> Err(const std::string& e) { _KsResult<T> r; r.ok=false; r.error=e; return r; }
};
inline _KsResult<std::string> _ks_file_read(const std::string& p){
    std::ifstream f(p);if(!f)return _KsResult<std::string>::Err("cannot open: "+p);
    std::ostringstream ss;ss<<f.rdbuf();return _KsResult<std::string>::Ok(ss.str());}
inline _KsResult<std::string> _ks_file_write(const std::string& p,const std::string& c){
    std::ofstream f(p,std::ios::trunc);if(!f)return _KsResult<std::string>::Err("cannot write: "+p);
    f<<c;return _KsResult<std::string>::Ok("");}
inline _KsResult<std::string> _ks_file_append(const std::string& p,const std::string& c){
    std::ofstream f(p,std::ios::app);if(!f)return _KsResult<std::string>::Err("cannot append: "+p);
    f<<c;return _KsResult<std::string>::Ok("");}
inline bool _ks_file_exists(const std::string& p){std::ifstream f(p);return f.good();}
inline _KsResult<std::string> _ks_file_delete(const std::string& p){
    return std::remove(p.c_str())==0?_KsResult<std::string>::Ok("")
        :_KsResult<std::string>::Err("cannot delete: "+p);}
inline _KsResult<std::vector<std::string>> _ks_file_lines(const std::string& p){
    std::ifstream f(p);if(!f)return _KsResult<std::vector<std::string>>::Err("cannot open: "+p);
    std::vector<std::string> out;std::string l;
    while(std::getline(f,l))out.push_back(l);
    return _KsResult<std::vector<std::string>>::Ok(out);}
inline int _ks_str_len(const std::string& s){return(int)s.size();}
inline std::vector<std::string> _ks_str_split(const std::string& s,const std::string& d){
    std::vector<std::string> r;size_t p=0,f;
    while((f=s.find(d,p))!=std::string::npos){r.push_back(s.substr(p,f-p));p=f+d.size();}
    r.push_back(s.substr(p));return r;}
inline std::string _ks_str_trim(const std::string& s){
    auto l=s.find_first_not_of(" \t\n\r");auto r=s.find_last_not_of(" \t\n\r");
    return l==std::string::npos?"":s.substr(l,r-l+1);}
inline bool _ks_str_contains(const std::string& s,const std::string& sub){return s.find(sub)!=std::string::npos;}
inline std::string _ks_str_replace(const std::string& s,const std::string& f,const std::string& t){
    std::string r=s;size_t p=0;
    while((p=r.find(f,p))!=std::string::npos){r.replace(p,f.size(),t);p+=t.size();}return r;}
inline bool _ks_str_starts(const std::string& s,const std::string& p){return s.rfind(p,0)==0;}
inline bool _ks_str_ends(const std::string& s,const std::string& e){
    return s.size()>=e.size()&&s.compare(s.size()-e.size(),e.size(),e)==0;}
inline std::string _ks_str_upper(std::string s){for(auto&c:s)c=toupper(c);return s;}
inline std::string _ks_str_lower(std::string s){for(auto&c:s)c=tolower(c);return s;}
inline std::string _ks_str_substr(const std::string& s,int p,int l){return s.substr(p,l);}
inline int _ks_str_toInt(const std::string& s){return std::stoi(s);}
inline float _ks_str_toFloat(const std::string& s){return std::stof(s);}
inline bool _ks_str_isEmpty(const std::string& s){return s.empty();}
template<typename C,typename V> inline bool _ks_has(const C& c,const V& v){return std::find(c.begin(),c.end(),v)!=c.end();}
template<typename K,typename MV,typename Q> inline bool _ks_has(const std::unordered_map<K,MV>& m,const Q& k){return m.count(K(k))>0;}
#endif // _KS_STDLIB_HELPERS_DEFINED

namespace { struct _KSInit {
    _KSInit() { std::cout << std::boolalpha << std::unitbuf; }
} _ks_init; }


int main() {
    int32_t sum = 0;
    for (int32_t i = 0; i < 10; i++) {
        sum += i;
    }
    for (int32_t j = 1; j <= 5; j++) {
        sum += j;
    }
}

